### ISSUE TITLE
ghcr.io/clusternet/clusternet-hub:v0.4.0 manifest unknown;image can not be found

### ISSUE THREAD

**Issue by miaowukong** [clusternet/clusternet#113]
#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
Clusternet v0.4.0 is officially released.
