### ISSUE TITLE
roadmap adbout clusternet?

### ISSUE THREAD

**Issue by silenceper** [clusternet/clusternet#118]
#### Why is this needed:
Want to know the roadmap of this project, for example, including cross-cluster service discovery.

**Comment by dixudx** [comment]
Will be added shortly. Thanks for watching.

**Comment by lichenglife** [comment]
Now it seems that clusternet just distributes resources to different clusters.In the future, can I view the resource status in the management cluster instead of going to childCluster?

**Comment by dixudx** [comment]
> can I view the resource status in the management cluster instead of going to childCluster?

Yes, this is planned and possibly released into v0.5.0 (next release).
