### ISSUE TITLE
failed to create ClusterRegistrationRequest: serializer for text/html; charset=utf-8 doesn't exist

### ISSUE THREAD

**Issue by bcaayat** [clusternet/clusternet#120]
failed to create ClusterRegistrationRequest: serializer for text/html; charset=utf-8 doesn't exist

#### What happened:
child register failed.
#### Anything else we need to know?:
agentlog:
I0909 02:47:53.941839       1 agent.go:215] try to bootstrap cluster registration if needed
I0909 02:47:53.942325       1 agent.go:407] generate a random string "clusternet-cluster-6dpgk" as cluster name for later use
E0909 02:47:53.958818       1 agent.go:193] failed to create ClusterRegistrationRequest: serializer for text/html; charset=utf-8 doesn't exist
W0909 02:47:53.958841       1 agent.go:194] something went wrong when using existing parent cluster credentials, switch to use bootstrap token instead

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):v0.3.0
    - Clusternet-hub version (user `clusternet-hub --version=json`):v0.3.0
- Kubernetes version (use `kubectl version`):v1.18.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by chenkaiyue** [comment]
I have tested with the same k8s verison, and it works well
<img width="1012" alt="wecom-temp-3e114dcff1d46473e3b2272b3e69bcf9" src="https://user-images.githubusercontent.com/15925403/132839210-3c47e4ff-9a43-4fbd-a43d-26f03a7b7e67.png">

I found that your parenturl is an Intranet IP. Please make sure  that the parenturl should be accessible to the managed cluster.
