### ISSUE TITLE
Ability to reconcile/rollback changes in child cluster

### ISSUE THREAD

**Issue by panpan0000** [clusternet/clusternet#135]
This issue was a part of previous https://github.com/clusternet/clusternet/issues/128

===================
I'm proposing a way :the agent will watch the desc and reconcile that deployment to original state (aka, rollback any change in child cluster and restore to hub cluster config)
hub cluster can override the difference which child cluster made. just like KubeFed.
and moreover , when I accidentally delete the deployment from child cluster , I'm looking forward clusternet can restore it back .

**Comment by panpan0000** [comment]
@dixudx  mentioned:

> I think the situation here might be a bit different, as the pic in this artice shows: users can exists in child cluster, so 
> personally i think it is reasonable to make changes in child cluster directly.


It's reasonable in Edge situation.
But there's not only day 1 but day 2 for  Application LCM .
Assuming below case:

(1) in Hub Cluster, admin distribute an app to all clusters
(2) in Child Cluster,  another one modify the app, example, changing its label or cpu limit
(3) In Hub Cluster, admin update the app (e.g. from v1.0 to v2.0)
(4) the change in step 2 will be lost.

Aka, Double-Head management will be a problem.

**Comment by dixudx** [comment]
Good scenarios. 👍👍👍 @panpan0000 

`clusternet-agent` needs to watch the resource changes and sync back the diffs.

**Comment by lmxia** [comment]
Very interesting. If it is possible, I want to on it.
Here is my thought, need more discussion.
1.  deployer in `clusternet-agent` need a `map[*metav1.APIResource] ResourceInformer`  to watch the resource changes
2.  enqueue the `namespacedname` of the associated `Description`.

however, now we can't resolve out the `Description` name from the raw content in the `Description`.
we can Set Annotations with Description namespacedname info into the raw objet when `clusternet-agent` Create the raw obj.

**Comment by dixudx** [comment]
@lmxia Yes, and we also need to consider,

1. The configuration diffs between other clusters. It seems `Localization` could help solve this. Or a fix-named `Localization` could be used to help sync and aggregate all the diffs from a child cluster.
