### ISSUE TITLE
clusternet proxy should not response 301 to ask client redirect

### ISSUE THREAD

**Issue by leoryu** [clusternet/clusternet#161]
#### What happened:

default go client enable the redirect func, but clusternet proxy will response 301 with a internal IP, which the client can't access.

<img width="1062" alt="企业微信截图_fa053d57-7d90-41aa-ad26-c14ce5ac3772" src="https://user-images.githubusercontent.com/34183243/138430027-683d0c60-072b-4ce2-aef1-351fdddc64f4.png">

#### What you expected to happen:

should not response 301.

#### How to reproduce it (as minimally and precisely as possible):

curl -s -f -I -L -k https://{pub_IP}:6443/apis/proxies.clusternet.io/v1alpha1/sockets/xxxxxxxx/proxy/direct

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
close this issue.

@leoryu Feel free to reopen this if you've got any questions.
