### ISSUE TITLE
Whether to support multiple control plane

### ISSUE THREAD

**Issue by lucming** [clusternet/clusternet#190]
i just want to ensure if global cluster breakdown,can we make a work cluster to be global cluster,just like redis.
it can't provide service if global cluster breakdown and have have only one global cluster

**Comment by dixudx** [comment]
If you want such highly available, you could set a cluster across multiple zones/regions with a [GSLB](https://avinetworks.com/glossary/global-server-load-balancing-2/). This will help keep your cluster available furthest.

And then deploying Clusternet with multiple replicas.

**Comment by lucming** [comment]
but it will affect the performance of the etcd for different zones

**Comment by dixudx** [comment]
Now all clusternet components can be deployed with multiple replicas. This can help improve the high availability.

But if the hub Kubernetes cluster crashes down, there is nothing we can do.

**Comment by lucming** [comment]
> Now all clusternet components can be deployed with multiple replicas. This can help improve the high availability.
> 
> But if the hub Kubernetes cluster crashes down, there is nothing we can do.

en, thanks for your reply :)
