### ISSUE TITLE
Decouple the hard relationship and make clusters relation programmable

### ISSUE THREAD

**Issue by lmxia** [clusternet/clusternet#192]
#### What would you like to be added:
Don't specify the parent cluster url when agent starts, Use a CRD like "Target"、“Parent” to Store the parent url adress.
#### Why is this needed:
So we can decouple the hard relationship, and give a change to  **program** the structure of Cluster resources, **program** means we can init/edit as will.

**Comment by dixudx** [comment]
> give a change to program the structure of Cluster resources, program means we can init/edit as will.

For now, Clusternet has two CRDs, `ClusterRegistrationRequest` and `ManagedCluster` that can be used to represent cluster metadata.

> Use a CRD like "Target"、“Parent” to Store the parent url adress.
> program the structure of Cluster resources, program means we can init/edit as will.

Could but not recommended. A lot of cases should be handled first. If we switch the parent url from one to another, 

1. the resources that deployed from previous parent clusters should be kept still or deleted?
2. the resource overrides from both sides conflicted. How to choose the right one?
3. The legacy objects, like `ClusterRegistrationRequest`, dedicated namespaces, etc, should be cleaned up as well
4. clusternet agents are usually deployed with multiple replicas. During switching, if one replica loses election, another replica with old configs will be elected again and connect with previous parent cluster. This will definitely lead to conflicts when coordinating resources.
5. etc

**Comment by lmxia** [comment]
Yes, that's deep consideration.
