### ISSUE TITLE
Is there a community exchange group？

### ISSUE THREAD

**Issue by hansongChina** [clusternet/clusternet#195]
Is there a community exchange group？Wechat, QQ or whatever？ @dixudx

**Comment by dixudx** [comment]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/5449021/145163319-cf938cd8-27c5-4b2c-9044-9b401779c76b.png">

We do have one wechat group. Feel free to join in. Welcome.

**Comment by hansongChina** [comment]
Qr code has expired, send it again?

**Comment by hansongChina** [comment]
Or pull me into a group? My wechat account is "sunloveworld"

**Comment by hansongChina** [comment]
@dixudx
