### ISSUE TITLE
Execute the "examples/ Applications" example, not deployed to the application to multiple clusters

### ISSUE THREAD

**Issue by hansongChina** [clusternet/clusternet#196]
#### What happened:
Execute the "examples/ Applications" example, not deployed to the application to multiple clusters
#### What you expected to happen:
Execute the "examples/ Applications" example to deploy the application to the multiple clusters as normal
#### How to reproduce it (as minimally and precisely as possible):
step1: find cluster-id
![image](https://user-images.githubusercontent.com/7590000/145164756-97b1e671-3e2c-4f0e-98f3-353c6012560a.png)

step2: modify Subscription clusters.clusternet.io/cluster-id and modify Localization namespace
![image](https://user-images.githubusercontent.com/7590000/145164259-355cd7f1-3b79-4a01-9255-c6d52c8eb2ae.png)
![image](https://user-images.githubusercontent.com/7590000/145164537-936a709b-6a1a-49b4-973d-7b9622441df9.png)
step3: cd clusternet/examples/Applications && kubectl clusternet apply -f .
![image](https://user-images.githubusercontent.com/7590000/145164891-186b312e-8c69-4236-abef-13a419feece5.png)
step4 checking , kubectl clusternet get desc -A ,No resources found
![image](https://user-images.githubusercontent.com/7590000/145165080-7c1561fc-da36-46ee-bb6c-538169ee8a43.png)

#### Anything else we need to know?:
Test in a K3S environment created by K3D
#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):v0.6.0
    - Clusternet-hub version (user `clusternet-hub --version=json`):v0.6.0
- Kubernetes version (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
- Linux lpai-dev-test-0-1a15g 5.15.6-1.el7.elrepo.x86_64 #1 SMP Tue Nov 30 12:36:34 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by dixudx** [comment]
It was caused by environment misconfiguration. Already solved.
