### ISSUE TITLE
Cannot find k8sapiserver pod with  label "app.kubernetes.io/componment"

### ISSUE THREAD

**Issue by fangyuchen86** [clusternet/clusternet#223]
#### What happened:
Clusternet use label "component" to find the apiserver pod, which is created by kubeadm. But the k8s suggest use "app.kubernetes.io/component" to label k8sapiserver. 

#### What you expected to happen:
Support both "component" and "app.kubernetes.io/component"

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by aiot** [comment]
The labels recommended by kubernetes can be found at https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

**Comment by dixudx** [comment]
> Clusternet use label "component" to find the apiserver pod, which is created by kubeadm. But the k8s suggest use "app.kubernetes.io/component" to label k8sapiserver.

IIUC, the status manager in `clusternet-agent` could locate the right `kube-apiserver` to get the settings for reporting, due to the `kube-apiserver` may use other labels.

**Comment by dixudx** [comment]
@fangyuchen86 Would you please help submit a PR fixing this?

**Comment by fangyuchen86** [comment]
OK
> @fangyuchen86 Would you please help submit a PR fixing this?
