### ISSUE TITLE
Error: unknown shorthand flag: 'n' in -n (kubectl clusternet get subs -n test)

### ISSUE THREAD

**Issue by svolence** [clusternet/clusternet#228]
#### What happened:
# Error: unknown shorthand flag: 'n' in -n
#### Environment:
- Clusternet version:

```bash
# kubectl clusternet version
{
  "gitVersion": "0.5.0",
  "gitCommit": "8eab4a2e0f64df9f6afe895f2e8eeddcc41b15ac",
  "buildDate": "2021-12-23T08:49:57Z",
  "platform": "linux/amd64"
}
```

**Comment by dixudx** [comment]
This is a bug of `kubectl-clusternet`.

Fixed in [kubectl-clusternet](https://github.com/clusternet/kubectl-clusternet) v0.5.1.

Please run `kubectl krew upgrade clusternet`.
