### ISSUE TITLE
TAG-Runtime presentation/discussion

### ISSUE THREAD

**Issue by raravena80** [clusternet/clusternet#229]
Hello Clusternet team,

I'm one of the co-chairs of the CNCF TAG-Runtime. I believe you had an agenda item to present the project in our meeting. I'm following up, I think it would be great for you to present/discuss the project in the future.

Feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com) at your convenience. 

Thanks!

**Comment by dixudx** [comment]
@raravena80 Thanks for reaching out. We'd like to have such a presentation.

Currently Jan 20th has been taken by OCM. And Chinese spring festivals will start from Jan 31st to Feb 6th. So I'd prefer to present [Clusternet](https://github.com/clusternet/clusternet) on Feb 17th.

**Comment by dixudx** [comment]
Already done.

Close.
