### ISSUE TITLE
changes not rolled back in child cluster when working in Dual/Push syncMode

### ISSUE THREAD

**Issue by dixudx** [clusternet/clusternet#236]
#### What happened:
When child clusters are running with syncMode `Push`/`Dual`, changes will not be rolled back as expected.

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`): v0.7.0
    - Clusternet-hub version (user `clusternet-hub --version=json`): v0.7.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by lmxia** [comment]
i will work on this issue
