### ISSUE TITLE
支持statefulset的多集群分发吗？

### ISSUE THREAD

**Issue by mrningyang** [clusternet/clusternet#245]
支持statefulset的多集群分发吗，比如一个statefulset有6个pod，在a,b,c三个集群分别为2个pod，分别为0-1，2-3，4-5。目前是怎么实现的，通过hub cluster作协调吗，某个集群怎么知道自己负责的statefulset序号应该是多少。

**Comment by dixudx** [comment]
> 在a,b,c三个集群分别为2个pod，分别为0-1，2-3，4-5


@mrningyang  这种做不到，也不太能做到。像 StatefulSet 这种序号，只能做到 a 集群部署一个 statefulset 副本为2，b集群一个statefulset 副本数为2。这个本质上是由于 Statefulset 的特定设计所限定的，没办法指定序列号进行创建。

如果是这种需求，我建议是自己定义一个类似于 StatefulSet 的 CRD 类型，可以支持指定序列号的起始。

**Comment by mrningyang** [comment]
> 



> > 在a,b,c三个集群分别为2个pod，分别为0-1，2-3，4-5
> 
> @mrningyang 这种做不到，也不太能做到。像 StatefulSet 这种序号，只能做到 a 集群部署一个 statefulset 副本为2，b集群一个statefulset 副本数为2。这个本质上是由于 Statefulset 的特定设计所限定的，没办法指定序列号进行创建。
> 
> 如果是这种需求，我建议是自己定义一个类似于 StatefulSet 的 CRD 类型，可以支持指定序列号的起始。

**Comment by mrningyang** [comment]
> > 在a,b,c三个集群分别为2个pod，分别为0-1，2-3，4-5
> 
> @mrningyang 这种做不到，也不太能做到。像 StatefulSet 这种序号，只能做到 a 集群部署一个 statefulset 副本为2，b集群一个statefulset 副本数为2。这个本质上是由于 Statefulset 的特定设计所限定的，没办法指定序列号进行创建。
> 
> 如果是这种需求，我建议是自己定义一个类似于 StatefulSet 的 CRD 类型，可以支持指定序列号的起始。

好的感谢，了解到这里的实现了
