### ISSUE TITLE
 support both  /healthz and /readyz 

### ISSUE THREAD

**Issue by rootdeep** [clusternet/clusternet#249]
#### What would you like to be added:

In lower k8s version, such as `1.14.3` ,  tke cluster doesn't provide path `/readyz` for clusternet agent to check cluster's health. Once clusternet agent runs on the cluster,  agent will report `readyz` as "false" value to  hub. It's a false positive error.

Can we use both `/readyz` and `/healthz`  to check cluster's health. Once one of them give an `ok` response, 
the cluster will be considered as healthy.

#### Why is this needed:

There are still many k8s clusters with lower k8s version at present,  use `/healthz` to give a compatible support with those clusters.

**Comment by dixudx** [comment]
>

**Comment by dixudx** [comment]
> There are still many k8s clusters with lower k8s version at present, use /healthz to give a comaptible support with thoes clusters.
