### ISSUE TITLE
Does clusternet-hub support multi-replicas？

### ISSUE THREAD

**Issue by snstaberah** [clusternet/clusternet#259]
#### What would you like to be added:
I see the websocket server in clusternet-hub is implemented by remote-dialer，and the replicas is set to 1；remote-dialer support multi replicas by set peers，Does clusternet-hub support multi-replicas？ I didn't find  any doc and code about this question；

#### Why is this needed:
if there is only one replica of clusternet-hub，the performance is limited and HA is not supported

**Comment by dixudx** [comment]
Yes, this feature will be supported in the following releases.
Please keep watching this project. Thanks for the support.

**Comment by snstaberah** [comment]
got it，thanks
