### ISSUE TITLE
why add prefix to resource names

### ISSUE THREAD

**Issue by jasine** [clusternet/clusternet#267]
#### What happened:

after deploying app by helm chart through clusternet, all resource names prefixed with subscription name and namespace, and I think it's unnecessary,  it may cause error when svc or deploy name is hard coded. 

below is the difference between manually installed by helm and installed by clusternet

![image](https://user-images.githubusercontent.com/1934966/158945699-bc867966-8ceb-4e09-a2c9-79fa7b83619f.png)

#### What you expected to happen:

keep original name of helm chart resources

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`): v0.8.0
    - Clusternet-hub version (user `clusternet-hub --version=json`): v0.8.0

**Comment by jasine** [comment]
sorry, resource prefix may added by the helm chart itself, my own chart looks normal, but the helm release name still prefixed, and maybe that's unnecessary neither

**Comment by dixudx** [comment]
> the helm release name still prefixed, maybe a name override config is better

Yeah, that makes sense.

With #269, the new release name will be the same value as `HelmChart` name. That means you can declare your desired released name as `HelmChart` object name.
