### ISSUE TITLE
kube config file management of child cluster

### ISSUE THREAD

**Issue by jasine** [clusternet/clusternet#275]
#### What would you like to be added:

store kube config file of child cluster in parent cluster and using it when specify a clusterid in  clusternet plugin

#### Why is this needed:

collecting, storing and managing kube config file is more  complicated when there many child clusters, thus if clusternet-agent can mount a path where child kube config file exist and  upload it to parent cluster and create a secret  in the corresponding namespace is more convenient. clusternet plugin can use it directly.

**Comment by dixudx** [comment]
> if clusternet-agent can mount a path where child kube config file exist and upload it to parent cluster and create a secret in the corresponding namespace is more convenient.

Actually such a secret named `child-cluster-deployer` does exist in every dedicated namespace in parent cluster. Mostly we use this credential to deploy resources to child clusters. For other operators/controllers, they can build a client for a child cluster with this secret.

> using it when specify a clusterid in clusternet plugin

We can do this. But we need to take authentications & authorizations into considerations as well.

Currently `kubectl clusternet` plugin does provide a way to interact with child clusters.

```bash
$ kubectl clusternet --cluster-id=7dc5966e-6736-48dd-9a82-2e4d74d30443 --child-kubeconfig=./my-child-cluster.kubeconfig get ns
NAME                STATUS   AGE
clusternet-system   Active   4d20h
default             Active   24d
kube-node-lease     Active   24d
kube-public         Active   24d
kube-system         Active   24d
test-nginx          Active   11d
test-systemd        Active   11d
```

**Comment by jasine** [comment]
> > if clusternet-agent can mount a path where child kube config file exist and upload it to parent cluster and create a secret in the corresponding namespace is more convenient.
> 
> Actually such a secret named `child-cluster-deployer` does exist in every dedicated namespace in parent cluster. Mostly we use this credential to deploy resources to child clusters. For other operators/controllers, they can build a client for a child cluster with this secret.
> 
> > using it when specify a clusterid in clusternet plugin
> 
> We can do this. But we need to take authentications & authorizations into considerations as well.
> 
> Currently `kubectl clusternet` plugin does provide a way to interact with child clusters.
> 
> ```shell
> $ kubectl clusternet --cluster-id=7dc5966e-6736-48dd-9a82-2e4d74d30443 --child-kubeconfig=./my-child-cluster.kubeconfig get ns
> NAME                STATUS   AGE
> clusternet-system   Active   4d20h
> default             Active   24d
> kube-node-lease     Active   24d
> kube-public         Active   24d
> kube-system         Active   24d
> test-nginx          Active   11d
> test-systemd        Active   11d
> ```

@dixudx  can we modify the plugin to use `child-cluster-deployer` and no longer need to provide a `kubeconfig` file?

**Comment by dixudx** [comment]
> can we modify the plugin to use child-cluster-deployer and no longer need to provide a kubeconfig file?

If so, RBAC rules in child clusters should be taken into consideration. Using `admin` to visit child clusters is not suggested.

Below questions should be resolved before moving forward,

1. If we aggregates all the RBAC rules all to parent clusters, that will bring into much trouble for parent clusters when the number of child clusters turn to 100, 1k, 10k. And for every new/updated rule in child clusters, we need to sync it back to parent cluster.
2. In parent cluster, we need to make sure the user has the privileges to visit child clusters. Extra steps are needed, such as creating RBAC rules to indicate this kind of priviledge, new workflows to admit rule changes, etc. And scalability is still a big problem, even for several clusters. Lots of rules are needed to be provisioned. 
3. Keeping all the users existing in every cluster, that seems impossible. And the clusters may be heterogeneous for different business needs, tenants, etc. Thus we need to allow child clusters having discrepant users. What's more, even the same user name may have different representation for child clusters.
4. and ...

**Comment by jasine** [comment]
thanks, it seems a long way,  I wrote a script as a workaround

**Comment by dixudx** [comment]
Close it.
Please feel free to reopen it if necessary.
