### ISSUE TITLE
parent cluster stuck/hang when child cluster join 

### ISSUE THREAD

**Issue by jasine** [clusternet/clusternet#284]
#### What happened:

1. when my k8s child cluster join to parent cluster, many errors occured on clusternet-hub and no resource created on  child cluster.

> clusternet-hub logs
![image](https://user-images.githubusercontent.com/1934966/161262278-a0198f7d-0c5a-4e24-9cf7-1d1d09d9de0c.png) 

3. when I restart the clusternet-hub pod, it will cause parent cluster node lose response soon(high cpu usage and disk io read), I have to reboot the node to recover. besides, after rebooting, the child cluster joined lastly will become normal and start to create corresponding resources  

> cvm monitor
![image](https://user-images.githubusercontent.com/1934966/161266885-156917d7-fe08-4130-9fed-9d74efb9f6a6.png)
  ![image](https://user-images.githubusercontent.com/1934966/161266938-8e7241d7-69eb-4989-b458-f36bd97100ab.png)

#### How to reproduce it (as minimally and precisely as possible):
when  k3s child cluster node join 

#### Environment:
- Clusternet version: 0.8.0
    - Clusternet-agent version: 0.8.0
    - Clusternet-hub version : 0.8.0
- Kubernetes version (use `kubectl version`): v1.20.6-tke.16(v1.22.7+k3s1)
- Cloud provider or hardware configuration: cvm of qcloud 
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04/ tencent os 
- Kernel (e.g. `uname -a`): 5.4.119-19-0009.1
- Others:

**Comment by dixudx** [comment]
![](https://user-images.githubusercontent.com/1934966/161265857-2244f19a-b3ef-416a-9c58-b6edb1cf235a.png)

The errors in this picture can be ignored. They are irrelevant.

**Comment by dixudx** [comment]
@jasine Could you elaborate your registration process? I did not get what happened exactly.

Also please help add annotations for each image, such as parent cluster, child cluster, clusternet components, etc.

**Comment by jasine** [comment]
@dixudx I changed the description and removed irrelevant log. 

my registration process:

1. I have a parent cluster (I tried k3s and qcloud hosted tke, they both have this problem), and installed clusternet-agent and clusternet-scheduler by helm with default values. 
2. I created some helm charts and subscriptions, and I wish when child cluster registered, they will create corresponding resources automatically    
3. I use serviceaccount token and follow helm value override to install clusternet-agent 
```bash
    helm install clusternet-agent -n clusternet-system --create-namespace \
        --set parentURL=${HOST} \
        --set registrationToken=${TOKEN} \
        --set replicaCount=1 \
        --set extraArgs.cluster-reg-name=$(hostname) \
        --set extraArgs.cluster-labels="accelerator=${accelerator}" \  #my custom label
        clusternet/clusternet-agent 
``` 
4. after clusternet-agent installation,
   - `clsrr` resource will be created in parent cluster and the status will be `Approved` 
   - `mcls` will be created in relevant namespace and `READYZ` is `true`
   - `description` will be created in relevant namespace, but `STATUS` is empty.
   - `helmrelease` not created in the relevant namespace
   -  from logs of `clusternet-agent`, the `description` is synced to child cluster
   - pod of `clusternet-hub` has following error logs
   > ![image](https://user-images.githubusercontent.com/1934966/161298131-9520bb46-839e-4074-ab17-fe67545bf6aa.png)

5. wait for a long time is  useless, so I have to restart pod of `clusternet-hub` , but when the new pod up, it will cause parent cluster node lose response soon(high cpu usage and disk io read), I have to reboot the node to recover. 
6. after the node rebooting, everything works.

so, I think there two problems:
1. why `description` is not `Success` and `helmrelease` not created after child cluster registration
2. why restart pod of `clusternet-hub` stuck the node

first problem is more important

**Comment by dixudx** [comment]
> "failed to transform Manifest: Internal error occurred"

Please check whether `clustern-hub` could access `kube-apiserver` in parent cluster.

**Comment by victory460** [comment]
> > "failed to transform Manifest: Internal error occurred"
> 
> Please check whether `clustern-hub` could access `kube-apiserver` in parent cluster.

How to config kube-apiserver address in `clustern-hub ` ?

**Comment by dixudx** [comment]
> How to config kube-apiserver address in `clustern-hub ` ?

By default `clusternet-hub` use in-cluster config to visit `kube-apiserver`. You can set explicit kubeconfig by flag `--kubeconfig` as well.
