### ISSUE TITLE
usage for shadow apiserver

### ISSUE THREAD

**Issue by snstaberah** [clusternet/clusternet#337]
#### What would you like to be added:
need docs  for shadow apiserver featuregate
#### Why is this needed:
I found a featuregate flag in clusternet-hub  deployment file
![image](https://user-images.githubusercontent.com/8952747/168971221-9dc92b0b-f56b-4386-ab6c-0dbbaccb15f4.png)

but i didn't found any doc to explain  the function of this ShadowAPI，and when should we set it to true/false；

i read the code，this shadow apiserver probably  launch an apiserver to make a copy of raw apis，but i can't get why we need to do this； 
can somebody please  explain the feature-gate of  ShadowAPI？ thanks

**Comment by dixudx** [comment]
@snstaberah  In short, if you want to deploy multi cluster resources, you need to enable this feature gate `ShadowAPI`. With this feature gate, you can create a `Deployment` in `kube-apiserver`, while this deployment is only visible to Clusternet. That's why I call it shadow api.

You can view this deployment with clusternet plugin.

```bash
kubectl clusternet get deploy
```

**Comment by snstaberah** [comment]
thanks，but why i need to create a deployment is only visible to Clusternet？and how to create such a deployment？i see examples in  examples/applications/，and the deployment  seems just like the normal deployment；  Does it means when i create a  normal deployment in kube-apiserver，the clusternet will auto create another shadow one in clusternet schema and scope？

**Comment by dixudx** [comment]
> thanks，but why i need to create a deployment only visible to Clusternet

Clusternet runs as an add-on to manage multi clusters. We do need to way to distinguish those objects from those in `kube-apiserver`. For example, if you create a deployment with `kubectl create deployment xxx`, then this deployment will run in current cluster immediately. But this is not what we want. We want to deploy this deployment to multi clusters, not current single cluster.

> and how to create such a deployment？i see examples in examples/applications/

`kubectl clusternet apply -f examples/applications/`

>  Does it means when i create a normal deployment in kube-apiserver，the clusternet will auto create another shadow one in clusternet schema and scope？

No.

> or create shadow objects only with thekubectl clusternet apply command？

Yes. `kubectl clusternet create/delete/edit/apply/scale/xxx` works the same with those in `kubectl`.

**Comment by snstaberah** [comment]
understood，thanks
