### ISSUE TITLE
Bug report in "PARENTURL"

### ISSUE THREAD

**Issue by SLZ0106** [clusternet/clusternet#37]
#### What happened:
when we execute the step "PARENTURL=https://192.168.10.10 REGTOKEN=07401b.f395accd246ae52d envsubst < ./deploy/templates/clusternet_agent_secret.yaml | kubectl apply -f -", the cmd report that "'PARENTURL' is not recognized as an internal or external command" in the file folder "clusternet-main". And when we execute this command in the subfolder "deploy/agent", the cmd report thet "the system cannot find the path specified."
#### What you expected to happen:
we can create this secret successfully.
#### How to reproduce it (as minimally and precisely as possible):
do everything  in "Get Started" step by step.
#### Environment:
- Clusternet version: v.0.2.0
    - Clusternet-agent version (user `clusternet-agent --version=json`): v.0.2.0
    - Clusternet-hub version (user `clusternet-hub --version=json`): v.0.2.0
- Kubernetes version (use `kubectl version`): v.1.21.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Bryceknows** [comment]
I tried `PARENTURL=https://rancher-ieo-prd-dur.darkside.cec.lab.emc.com/k8s/clusters/c-n9f2q REGTOKEN=07401b.f395accd246ae52d envsubst < ./deploy/templates/clusternet_agent_secret.yaml | kubectl apply -f -` , and bash reported "secret/clusternet-agent-cluster-registration configured" (I think this should be right). However, when I used `kubectl get clsrr` to check cluster registrations, the bash reported "No resources found". I also tried `kubectl get clsrr clusternet-dc91021d-2361-4f6d-a404-7c33b9e01118 -o yaml` , and it reported "Error from server (NotFound): clusterregistrationrequests.clusters.clusternet.io "clusternet-dc91021d-2361-4f6d-a404-7c33b9e01118" not found".

**Comment by dixudx** [comment]
> the cmd report that "'PARENTURL' is not recognized as an internal or external command" in the file folder "clusternet-main".

@SLZ0106 Actually this is a common error of `envsubst`. Please make sure [envsubst is installed successfully](https://command-not-found.com/envsubst). You can reinstall it if needed.

Also please help check your `SHELL` by `env | grep SHELL`.

Try `PARENTURL=https://192.168.10.10 REGTOKEN=07401b.f395accd246ae52d envsubst < ./deploy/templates/clusternet_agent_secret.yaml` to see the output.

**Comment by dixudx** [comment]
> However, when I used kubectl get clsrr to check cluster registrations, the bash reported "No resources found".

**Comment by dixudx** [comment]
> I also tried kubectl get clsrr clusternet-dc91021d-2361-4f6d-a404-7c33b9e01118 -o yaml , and it reported "Error from server (NotFound): clusterregistrationrequests.clusters.clusternet.io "clusternet-dc91021d-2361-4f6d-a404-7c33b9e01118" not found".

**Comment by Bryceknows** [comment]
> > I also tried kubectl get clsrr clusternet-dc91021d-2361-4f6d-a404-7c33b9e01118 -o yaml , and it reported "Error from server (NotFound): clusterregistrationrequests.clusters.clusternet.io "clusternet-dc91021d-2361-4f6d-a404-7c33b9e01118" not found".

Should I modify the URL or just use `https://192.168.10.10`?

**Comment by dixudx** [comment]
@Bryceknows You just need to change these settings to yours.

**Comment by dixudx** [comment]
cc @joshuakwan

**Comment by joshuakwan** [comment]
> > > I also tried kubectl get clsrr clusternet-dc91021d-2361-4f6d-a404-7c33b9e01118 -o yaml , and it reported "Error from server (NotFound): clusterregistrationrequests.clusters.clusternet.io "clusternet-dc91021d-2361-4f6d-a404-7c33b9e01118" not found".
> 
> Should I modify the URL or just use `https://192.168.10.10`?

As we discussed, please try with 2 minikube clusters locally first before going to the staging env.

**Comment by Bryceknows** [comment]
Thanks. I will try.
