### ISSUE TITLE
add intermediate states when install/update a helm chart

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#380]
#### What would you like to be added:
example:
add a install-pending state after trigger a helm install
add a upgrade-pending state after trigger a helm upgrade

**Comment by huxiaoliang** [comment]
@DanielXLee  please  also include helm rollback

**Comment by DanielXLee** [comment]
@huxiaoliang The current design don's support rollback like helm CLI rollback. We can use helm upgrade to rollback to an older version
