### ISSUE TITLE
support helm install flags

### ISSUE THREAD

**Issue by wl-chen** [clusternet/clusternet#402]
#### What would you like to be added:
I hope that clusternet supports helm install flags options when installing chart. 
#### Why is this needed:
helm chart install timeout time is default 5 mintues. If this time is exceeded, it will return failure. But my localization's installazition needs more 5 minutes sometimes. And now clusternet dont support helm install flags. So i cant use --timeout or --wait flags to Increase waiting time.

**Comment by wl-chen** [comment]
> > But my localization's installazition needs more 5 minutes sometimes. And now clusternet dont support helm install flags. So i cant use --timeout or --wait flags to Increase waiting time.
> 
> @wl-chen I think we can add a new field in `HelmChart` CRD object, where a default timeout value can be set. And we can override this default value in `Localization` when needed.
> 
> Would you like to implement this feature?

@dixudx In addition to the timeout value, can you add a --wait value? 
<img width="1258" alt="wecom-temp-bdb917ad7e08c59f9ecfc80ea11c79e4" src="https://user-images.githubusercontent.com/27396108/177237460-9d12b095-e473-4952-9005-d15e501b746c.png">

**Comment by dixudx** [comment]
> In addition to the timeout value, can you add a --wait value?

`--wait` and `--timeout` are usually used together. I'm fine to add these two new fields.

@wl-chen Please feel free to implement this if you're interested.

**Comment by wl-chen** [comment]
> > In addition to the timeout value, can you add a --wait value?
> 
> `--wait` and `--timeout` are usually used together. I'm fine to add these two new fields.
> 
> @wl-chen Please feel free to implement this if you're interested.

ok, i will try it~

**Comment by dixudx** [comment]
@wl-chen Any progress on this new feature?

**Comment by wl-chen** [comment]
> @wl-chen Any progress on this new feature?

I've been busy lately, this week or next week.

**Comment by wl-chen** [comment]
> @wl-chen Any progress on this new feature?

I want to add an annotation (helm chart timeout value) on helmchart resources. And chart when installing release can read this annotation. What do you think of it?

**Comment by dixudx** [comment]
> I want to add an annotation (helm chart timeout value) on helmchart resources. And chart when installing release can read this annotation. What do you think of it?

I think we can add it to `HelmChartSpec`, and set a default timeout value.
