### ISSUE TITLE
The k8s cluster has custom scheduling logic, and FeedInventory needs to be extended

### ISSUE THREAD

**Issue by silenceper** [clusternet/clusternet#445]
#### What would you like to be added:
predictor has custom scheduling logic, depends on the annotation information of the pod, and needs FeedInventory to supplement the annotation information of the pod

**Comment by dixudx** [comment]
`FeedInventory` could be out-of-tree. You can disable feature gate `FeedInventory` when starting `clusternet-hub`.

Refer to [sample external feedinventory controller](https://github.com/clusternet/sample-controllers/tree/main/cmd/external-feedinventory).

**Comment by dixudx** [comment]
We can also implement our own logic on CRDs in out-of-tree `FeedInventory` controller.

**Comment by silenceper** [comment]
Got it, thanks!
