### ISSUE TITLE
`kubectl get clsrr` the server doesn't have a resource type "clsrr"

### ISSUE THREAD

**Issue by victory460** [clusternet/clusternet#446]
#### What happened:
Follow this guide of https://clusternet.io/docs/installation/install-the-hard-way:

kubectl get clsrr:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/30213558/183790489-587ea340-cae0-429c-ae3f-48c6a1aa2a95.png">

children:
![image](https://user-images.githubusercontent.com/30213558/183790231-b825654c-e747-4d3f-b6f5-65b07f9cf1b8.png)

parent:
![image](https://user-images.githubusercontent.com/30213558/183790150-1a60cec0-ec2b-411f-9e80-3655967ccbab.png)

![image](https://user-images.githubusercontent.com/30213558/183790207-15a32745-b4eb-492b-8c67-b9b9a4cc0b12.png)

#### What you expected to happen:
kubectl get clsrr list children 
#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
     ghcr.io/clusternet/clusternet-agent:v0.11.0

      ```
      [root@k8s-m-002 ~]# kubectl get deploy -n clusternet-system -o wide
      NAME               READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS         IMAGES                                        SELECTOR
      clusternet-agent   3/3     3            3           12h   clusternet-agent   ghcr.io/clusternet/clusternet-agent:v0.11.0   app=clusternet-agent
      ```

    - Clusternet-hub version (user `clusternet-hub --version=json`):
      ghcr.io/clusternet/clusternet-hub:v0.11.0 

      ```
          [root@k8s-m-001 ~]# kubectl get deploy -n clusternet-system -o wide
      NAME                   READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS             IMAGES                                            SELECTOR
      clusternet-hub         3/3     3            3           10h   clusternet-hub         ghcr.io/clusternet/clusternet-hub:v0.11.0         app=clusternet-hub
      clusternet-scheduler   3/3     3            3           10h   clusternet-scheduler   ghcr.io/clusternet/clusternet-scheduler:v0.11.0   app=clusternet-scheduler
      ```
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
  ```
  - NAME="CentOS Linux"
  VERSION="7 (Core)"
  ID="centos"
  ID_LIKE="rhel fedora"
  VERSION_ID="7"
  PRETTY_NAME="CentOS Linux 7 (Core)"
  ANSI_COLOR="0;31"
  CPE_NAME="cpe:/o:centos:centos:7"
  HOME_URL="https://www.centos.org/"
  BUG_REPORT_URL="https://bugs.centos.org/"
  
  CENTOS_MANTISBT_PROJECT="CentOS-7"
  CENTOS_MANTISBT_PROJECT_VERSION="7"
  REDHAT_SUPPORT_PRODUCT="centos"
  REDHAT_SUPPORT_PRODUCT_VERSION="7"
  ```
- Kernel (e.g. `uname -a`):    
    Linux k8s-m-001 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by dixudx** [comment]
@victory460 Have you run `kubectl apply -f deploy/hub`, where CRDs will be applied.

**Comment by victory460** [comment]
> kubectl apply -f deploy/hub

I have done it before.

```
[root@k8s-m-001 clusternet-main]# kubectl get deploy -n clusternet-system -o wide
NAME                   READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS             IMAGES                                            SELECTOR
clusternet-hub         3/3     3            3           11h   clusternet-hub         ghcr.io/clusternet/clusternet-hub:v0.11.0         app=clusternet-hub
clusternet-scheduler   3/3     3            3           11h   clusternet-scheduler   ghcr.io/clusternet/clusternet-scheduler:v0.11.0   app=clusternet-scheduler
[root@k8s-m-001 clusternet-main]# kubectl get pod -n clusternet-system -o wide
NAME                                    READY   STATUS    RESTARTS   AGE   IP             NODE        NOMINATED NODE   READINESS GATES
clusternet-hub-694784df67-wmmmh         1/1     Running   0          11h   100.118.3.18   k8s-m-001   <none>           <none>
clusternet-hub-694784df67-xlv6f         1/1     Running   0          11h   100.118.3.19   k8s-m-001   <none>           <none>
clusternet-hub-694784df67-zdz4l         1/1     Running   0          11h   100.118.3.17   k8s-m-001   <none>           <none>
clusternet-scheduler-7d47c9ddd4-4d6xf   1/1     Running   0          11h   100.118.3.22   k8s-m-001   <none>           <none>
clusternet-scheduler-7d47c9ddd4-5dxqn   1/1     Running   0          11h   100.118.3.21   k8s-m-001   <none>           <none>
clusternet-scheduler-7d47c9ddd4-cgbtr   1/1     Running   0          11h   100.118.3.20   k8s-m-001   <none>           <none>
```

**Comment by victory460** [comment]
clusternet-hub log:

[a.log](https://github.com/clusternet/clusternet/files/9295947/a.log)

**Comment by dixudx** [comment]
```
W0809 14:59:49.170178       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.FeedInventory: the server could not find the requested resource (get feedinventories.apps.clusternet.io)
W0809 14:59:49.170297       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Description: the server could not find the requested resource (get descriptions.apps.clusternet.io)
W0809 14:59:49.170340       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Base: the server could not find the requested resource (get bases.apps.clusternet.io)
E0809 14:59:49.170370       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.FeedInventory: failed to list *v1alpha1.FeedInventory: the server could not find the requested resource (get feedinventories.apps.clusternet.io)
E0809 14:59:49.170397       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Base: failed to list *v1alpha1.Base: the server could not find the requested resource (get bases.apps.clusternet.io)
W0809 14:59:49.170363       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Localization: the server could not find the requested resource (get localizations.apps.clusternet.io)
E0809 14:59:49.170445       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Localization: failed to list *v1alpha1.Localization: the server could not find the requested resource (get localizations.apps.clusternet.io)
E0809 14:59:49.170367       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Description: failed to list *v1alpha1.Description: the server could not find the requested resource (get descriptions.apps.clusternet.io)
W0809 14:59:49.170432       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.HelmRelease: the server could not find the requested resource (get helmreleases.apps.clusternet.io)
E0809 14:59:49.170513       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.HelmRelease: failed to list *v1alpha1.HelmRelease: the server could not find the requested resource (get helmreleases.apps.clusternet.io)
W0809 14:59:49.170708       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.HelmChart: the server could not find the requested resource (get helmcharts.apps.clusternet.io)
E0809 14:59:49.170733       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.HelmChart: failed to list *v1alpha1.HelmChart: the server could not find the requested resource (get helmcharts.apps.clusternet.io)
W0809 14:59:49.170755       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta2.FlowSchema: the server could not find the requested resource
E0809 14:59:49.170787       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta2.FlowSchema: failed to list *v1beta2.FlowSchema: the server could not find the requested resource
W0809 14:59:49.171557       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Subscription: the server could not find the requested resource (get subscriptions.apps.clusternet.io)
E0809 14:59:49.171581       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Subscription: failed to list *v1alpha1.Subscription: the server could not find the requested resource (get subscriptions.apps.clusternet.io)
W0809 14:59:49.171715       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Manifest: the server could not find the requested resource (get manifests.apps.clusternet.io)
E0809 14:59:49.171736       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Manifest: failed to list *v1alpha1.Manifest: the server could not find the requested resource (get manifests.apps.clusternet.io)
W0809 14:59:49.172398       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.ManagedCluster: the server could not find the requested resource (get managedclusters.clusters.clusternet.io)
E0809 14:59:49.172420       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.ManagedCluster: failed to list *v1beta1.ManagedCluster: the server could not find the requested resource (get managedclusters.clusters.clusternet.io)
W0809 14:59:49.172655       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Globalization: the server could not find the requested resource (get globalizations.apps.clusternet.io)
E0809 14:59:49.172669       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Globalization: failed to list *v1alpha1.Globalization: the server could not find the requested resource (get globalizations.apps.clusternet.io)
W0809 14:59:49.172768       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta2.PriorityLevelConfiguration: the server could not find the requested resource
E0809 14:59:49.172791       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta2.PriorityLevelConfiguration: failed to list *v1beta2.PriorityLevelConfiguration: the server could not find the requested resource
W0809 14:59:49.172898       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.ClusterRegistrationRequest: the server could not find the requested resource (get clusterregistrationrequests.clusters.clusternet.io)
E0809 14:59:49.172921       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.ClusterRegistrationRequest: failed to list *v1beta1.ClusterRegistrationRequest: the server could not find the requested resource (get clusterregistrationrequests.clusters.clusternet.io)
```

It seems the CRDs are not applied. Please check them.

```bash
kubectl get crd | grep clusternet
```

**Comment by victory460** [comment]
> ```
> W0809 14:59:49.170178       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.FeedInventory: the server could not find the requested resource (get feedinventories.apps.clusternet.io)
> W0809 14:59:49.170297       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Description: the server could not find the requested resource (get descriptions.apps.clusternet.io)
> W0809 14:59:49.170340       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Base: the server could not find the requested resource (get bases.apps.clusternet.io)
> E0809 14:59:49.170370       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.FeedInventory: failed to list *v1alpha1.FeedInventory: the server could not find the requested resource (get feedinventories.apps.clusternet.io)
> E0809 14:59:49.170397       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Base: failed to list *v1alpha1.Base: the server could not find the requested resource (get bases.apps.clusternet.io)
> W0809 14:59:49.170363       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Localization: the server could not find the requested resource (get localizations.apps.clusternet.io)
> E0809 14:59:49.170445       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Localization: failed to list *v1alpha1.Localization: the server could not find the requested resource (get localizations.apps.clusternet.io)
> E0809 14:59:49.170367       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Description: failed to list *v1alpha1.Description: the server could not find the requested resource (get descriptions.apps.clusternet.io)
> W0809 14:59:49.170432       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.HelmRelease: the server could not find the requested resource (get helmreleases.apps.clusternet.io)
> E0809 14:59:49.170513       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.HelmRelease: failed to list *v1alpha1.HelmRelease: the server could not find the requested resource (get helmreleases.apps.clusternet.io)
> W0809 14:59:49.170708       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.HelmChart: the server could not find the requested resource (get helmcharts.apps.clusternet.io)
> E0809 14:59:49.170733       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.HelmChart: failed to list *v1alpha1.HelmChart: the server could not find the requested resource (get helmcharts.apps.clusternet.io)
> W0809 14:59:49.170755       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta2.FlowSchema: the server could not find the requested resource
> E0809 14:59:49.170787       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta2.FlowSchema: failed to list *v1beta2.FlowSchema: the server could not find the requested resource
> W0809 14:59:49.171557       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Subscription: the server could not find the requested resource (get subscriptions.apps.clusternet.io)
> E0809 14:59:49.171581       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Subscription: failed to list *v1alpha1.Subscription: the server could not find the requested resource (get subscriptions.apps.clusternet.io)
> W0809 14:59:49.171715       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Manifest: the server could not find the requested resource (get manifests.apps.clusternet.io)
> E0809 14:59:49.171736       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Manifest: failed to list *v1alpha1.Manifest: the server could not find the requested resource (get manifests.apps.clusternet.io)
> W0809 14:59:49.172398       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.ManagedCluster: the server could not find the requested resource (get managedclusters.clusters.clusternet.io)
> E0809 14:59:49.172420       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.ManagedCluster: failed to list *v1beta1.ManagedCluster: the server could not find the requested resource (get managedclusters.clusters.clusternet.io)
> W0809 14:59:49.172655       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.Globalization: the server could not find the requested resource (get globalizations.apps.clusternet.io)
> E0809 14:59:49.172669       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Globalization: failed to list *v1alpha1.Globalization: the server could not find the requested resource (get globalizations.apps.clusternet.io)
> W0809 14:59:49.172768       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta2.PriorityLevelConfiguration: the server could not find the requested resource
> E0809 14:59:49.172791       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta2.PriorityLevelConfiguration: failed to list *v1beta2.PriorityLevelConfiguration: the server could not find the requested resource
> W0809 14:59:49.172898       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.ClusterRegistrationRequest: the server could not find the requested resource (get clusterregistrationrequests.clusters.clusternet.io)
> E0809 14:59:49.172921       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.ClusterRegistrationRequest: failed to list *v1beta1.ClusterRegistrationRequest: the server could not find the requested resource (get clusterregistrationrequests.clusters.clusternet.io)
> ```
> 
> It seems the CRDs are not applied. Please check them.
> 
> ```shell
> kubectl get crd | grep clusternet
> ```

Thanks! You are right. Why these crds not running? What can we do to solve this problem?
```
[root@k8s-m-001 clusternet-main]# kubectl get crd | grep clusternet
[root@k8s-m-001 clusternet-main]# kubectl get crd | grep ClusterRegistrationRequest
```

**Comment by dixudx** [comment]
Have you cloned the whole repo?

`kubectl apply -f deploy/hub` will apply all the resources in this folder, where CRDs are defined as well. These CRDs are using soft links to `../../manifests/crds`. You can take a check.

You can also directly apply with `kubectl apply -f manifests/crds` as well.

**Comment by victory460** [comment]
Thanks a lot.
