### ISSUE TITLE
installing kubectl plugin kubectl-clusternet, distribute application to child clusters failed

### ISSUE THREAD

**Issue by Sword-zhj** [clusternet/clusternet#448]
#### What happened:
After installing kubectl plugin [kubectl-clusternet](https://github.com/clusternet/kubectl-clusternet), we run below commands to distribute this application to child clusters，We get the following result

> subscription.apps.clusternet.io/app-demo configured
Error from server (ServiceUnavailable): error when retrieving current configuration of:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "foo", Namespace: ""
from server for: "foo.yaml": the server is currently unable to handle the request (get namespaces foo)
Error from server (ServiceUnavailable): error when retrieving current configuration of:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "my-nginx", Namespace: "foo"
from server for: "foo.yaml": the server is currently unable to handle the request (get deployments.apps my-nginx)
Error from server (ServiceUnavailable): error when retrieving current configuration of:
Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
Name: "my-nginx-svc", Namespace: "foo"
from server for: "foo.yaml": the server is currently unable to handle the request (get services my-nginx-svc)

#### What you expected to happen:

> resources running in each child clusters.

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):0.11.0
    - Clusternet-hub version (user `clusternet-hub --version=json`):0.11.0
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

> - NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

- Kernel (e.g. `uname -a`):

> Linux k8s-m-001 3.10.0-1160.25.1.el7.x86_64 https://github.com/clusternet/clusternet/issues/1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Others:

**Comment by Sword-zhj** [comment]
apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: foo
  labels:
    clusternet-app: multi-cluster-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  namespace: foo
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx
---
apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
  name: app-demo
  namespace: default
spec:
  subscribers: # defines the clusters to be distributed to
    - clusterAffinity:
        matchLabels:
          clusters.clusternet.io/cluster-id: 40e049fa-2c47-4148-93a7-6e4ecad6132a # PLEASE UPDATE THIS CLUSTER-ID TO YOURS!!!
  feeds: # defines all the resources to be deployed with
    - apiVersion: v1
      kind: Namespace
      name: foo
    - apiVersion: v1
      kind: Service
      name: my-nginx-svc
      namespace: foo
    - apiVersion: apps/v1
      kind: Deployment
      name: my-nginx
      namespace: foo

**Comment by dixudx** [comment]
> we run below commands to distribute this application to child clusters，We get the following result

Would you please share your commands here?

**Comment by Sword-zhj** [comment]
./kubectl-clusternet apply -f foo.yaml

**Comment by Sword-zhj** [comment]
> > we run below commands to distribute this application to child clusters，We get the following result
> 
> Would you please share your commands here?

./kubectl-clusternet apply -f foo.yaml

**Comment by Sword-zhj** [comment]
> > we run below commands to distribute this application to child clusters，We get the following result
> 
> Would you please share your commands here?

foo.yaml have provided above.

**Comment by Sword-zhj** [comment]
> ## apiVersion: v1
> kind: Namespace
> metadata:
> name: foo
> ## apiVersion: apps/v1
> kind: Deployment
> metadata:
> name: my-nginx
> namespace: foo
> labels:
> clusternet-app: multi-cluster-nginx
> spec:
> selector:
> matchLabels:
> app: nginx
> replicas: 2
> template:
> metadata:
> labels:
> app: nginx
> spec:
> containers:
> - name: nginx
> image: nginx:1.14.2
> ports:
> - containerPort: 80
> ## apiVersion: v1
> kind: Service
> metadata:
> name: my-nginx-svc
> namespace: foo
> labels:
> app: nginx
> spec:
> type: ClusterIP
> ports:
> - port: 80
> selector:
> app: nginx
> apiVersion: apps.clusternet.io/v1alpha1 kind: Subscription metadata: name: app-demo namespace: default spec: subscribers: # defines the clusters to be distributed to - clusterAffinity: matchLabels: clusters.clusternet.io/cluster-id: 40e049fa-2c47-4148-93a7-6e4ecad6132a # PLEASE UPDATE THIS CLUSTER-ID TO YOURS!!! feeds: # defines all the resources to be deployed with - apiVersion: v1 kind: Namespace name: foo - apiVersion: v1 kind: Service name: my-nginx-svc namespace: foo - apiVersion: apps/v1 kind: Deployment name: my-nginx namespace: foo

apiVersion: v1
kind: Namespace
metadata:
name: foo
apiVersion: apps/v1
kind: Deployment
metadata:
name: my-nginx
namespace: foo
labels:
clusternet-app: multi-cluster-nginx
spec:
selector:
matchLabels:
app: nginx
replicas: 2
template:
metadata:
labels:
app: nginx
spec:
containers:
- name: nginx
image: nginx:1.14.2
ports:
- containerPort: 80
apiVersion: v1
kind: Service
metadata:
name: my-nginx-svc
namespace: foo
labels:
app: nginx
spec:
type: ClusterIP
ports:
- port: 80
selector:
app: nginx
apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
name: app-demo
namespace: default
spec:
subscribers: # defines the clusters to be distributed to
- clusterAffinity:
matchLabels:
clusters.clusternet.io/cluster-id: 40e049fa-2c47-4148-93a7-6e4ecad6132a # PLEASE UPDATE THIS CLUSTER-ID TO YOURS!!!
feeds: # defines all the resources to be deployed with
- apiVersion: v1
kind: Namespace
name: foo
- apiVersion: v1
kind: Service
name: my-nginx-svc
namespace: foo
- apiVersion: apps/v1
kind: Deployment
name: my-nginx
namespace: foo

**Comment by Sword-zhj** [comment]
> > we run below commands to distribute this application to child clusters，We get the following result
> 
> Would you please share your commands here?

`apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: foo
  labels:
    clusternet-app: multi-cluster-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  namespace: foo
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx
---
apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
  name: app-demo
  namespace: default
spec:
  subscribers: # defines the clusters to be distributed to
    - clusterAffinity:
        matchLabels:
          clusters.clusternet.io/cluster-id: 40e049fa-2c47-4148-93a7-6e4ecad6132a # PLEASE UPDATE THIS CLUSTER-ID TO YOURS!!!
  feeds: # defines all the resources to be deployed with
    - apiVersion: v1
      kind: Namespace
      name: foo
    - apiVersion: v1
      kind: Service
      name: my-nginx-svc
      namespace: foo
    - apiVersion: apps/v1
      kind: Deployment
      name: my-nginx
      namespace: foo`

**Comment by Sword-zhj** [comment]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/32220271/183872080-6b2f8e6f-a403-4469-a1b8-ae40e0394be4.png">
 kubectl get mcls -A      result

**Comment by dixudx** [comment]
> Error from server (ServiceUnavailable): error when retrieving current configuration of:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "foo", Namespace: ""

It seems `kube-apiserver` cannot visit `clusternet-hub`.

> Since clusternet-hub is running as an AA, please make sure that parent apiserver could visit the clusternet-hub service.

You can take a test. `kubectl-clusternet get ns`. If error occurs, that means `clusternet-hub` is not accessible by `kube-apiserver`.

`clusternet-hub` exposes a cluster ip. Please make sure cluster ip works in your Kubernetes cluster.

**Comment by Sword-zhj** [comment]
imagechild cluster use private network ip parent cluster use public network ip. the agent sever logs like above. and a secret that contains token for cluster registration be created by command :
PARENTURL=https://36.133.135.247:6443/ REGTOKEN=07401b.f395accd246ae52d envsubst < ./deploy/templates/clusternet_agent_secret.yaml | kubectl apply -f -
36.133.135.247 is parent cluster public network ip. how do i deal with this error？
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/32220271/183912687-bf9a18b0-b943-4be9-8c41-c8a64ac201f1.png">

**Comment by Sword-zhj** [comment]
> > Error from server (ServiceUnavailable): error when retrieving current configuration of:
> > Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
> > Name: "foo", Namespace: ""
> 
> It seems `kube-apiserver` cannot visit `clusternet-hub`.
> 
> > Since clusternet-hub is running as an AA, please make sure that parent apiserver could visit the clusternet-hub service.
> 
> You can take a test. `kubectl-clusternet get ns`. If error occurs, that means `clusternet-hub` is not accessible by `kube-apiserver`.
> 
> `clusternet-hub` exposes a cluster ip. Please make sure cluster ip works in your Kubernetes cluster.

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/32220271/183913219-5dce4419-2219-4331-abe6-21165bdf0090.png">
parent cluster use public network ip. the agent sever logs like above. and a secret that contains token for cluster registration be created by command :
PARENTURL=https://36.133.135.247:6443/ REGTOKEN=07401b.f395accd246ae52d envsubst < ./deploy/templates/clusternet_agent_secret.yaml | kubectl apply -f -
36.133.135.247 is parent cluster public network ip. 
how do i deal with this error？

**Comment by dixudx** [comment]
Actually your kube-apiserver did not sign `36.133.135.247` into its key/cert pair. It is not a bug of Clusternet.

Plesse make sure the CA of `kube-apiserver` sign `36.133.135.247` into its public certificates.

**Comment by dixudx** [comment]
You can follow [Generate Kubernetes Certificates Manually](https://kubernetes.io/docs/tasks/administer-cluster/certificates/).

If you're using `kubeadm` to setup the cluster, please use a config when running `kubeadm init --config=myconfig.yml`, like follows,

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
...
apiServer:
  certSANs:
    - 36.133.135.247
...
```

Other parts of the config are omitted. Please take a look at `apiServer.certSANs`, where your public master ip can be set.

**Comment by Sword-zhj** [comment]
> You can follow [Generate Kubernetes Certificates Manually](https://kubernetes.io/docs/tasks/administer-cluster/certificates/).
> 
> If you're using `kubeadm` to setup the cluster, please use a config when running `kubeadm init --config=myconfig.yml`, like follows,
> 
> ```
> apiVersion: kubeadm.k8s.io/v1beta3
> kind: ClusterConfiguration
> ...
> apiServer:
>   certSANs:
>     - 36.133.135.247
> ...
> ```
> 
> Other parts of the config are omitted. Please take a look at `apiServer.certSANs`, where your public master ip can be set.

Thanks. Solved the problem according to your method

**Comment by Sword-zhj** [comment]
> > Error from server (ServiceUnavailable): error when retrieving current configuration of:
> > Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
> > Name: "foo", Namespace: ""
> 
> It seems `kube-apiserver` cannot visit `clusternet-hub`.
> 
> > Since clusternet-hub is running as an AA, please make sure that parent apiserver could visit the clusternet-hub service.
> 
> You can take a test. `kubectl-clusternet get ns`. If error occurs, that means `clusternet-hub` is not accessible by `kube-apiserver`.
> 
> `clusternet-hub` exposes a cluster ip. Please make sure cluster ip works in your Kubernetes cluster.



> > Error from server (ServiceUnavailable): error when retrieving current configuration of:
> > Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
> > Name: "foo", Namespace: ""
> 
> It seems `kube-apiserver` cannot visit `clusternet-hub`.
> 
> > Since clusternet-hub is running as an AA, please make sure that parent apiserver could visit the clusternet-hub service.
> 
> You can take a test. `kubectl-clusternet get ns`. If error occurs, that means `clusternet-hub` is not accessible by `kube-apiserver`.
> 
> `clusternet-hub` exposes a cluster ip. Please make sure cluster ip works in your Kubernetes cluster.


<img width="648" alt="image" src="https://user-images.githubusercontent.com/32220271/184055523-d7409810-5d6b-4495-930b-99132e4319cc.png">
I have successfully executed this command：  ./kubectl-clusternet apply -f foo.yaml 
bug in child clusters, I use the command:  kubectl get ns. can't find the ns created by parent cluster 
how can i check resources running status in each child clusters.

**Comment by dixudx** [comment]
> I use the command: kubectl get ns. can't find the ns created by parent cluster. 

Have the parent cluster registered itself as a child cluster?

> how can i check resources running status in each child clusters. 

Currently there are two ways to get the status. 

1. For deployment/statefulset/job resources, you can visit `Subscription` status to get an aggregated status from each child clusters. Such as [Checking Aggregated Status](https://clusternet.io/docs/tutorials/multi-cluster-apps/aggregated-status/).

2. Also you can check them directly in child clusters from parent cluster.

```bash
$ kubectl clusternet --cluster-id=7dc5966e-6736-48dd-9a82-2e4d74d30443 \
 --child-kubeconfig=./your-child-cluster-kubeconfig get ns
```

**Comment by Sword-zhj** [comment]
> > I use the command: kubectl get ns. can't find the ns created by parent cluster.
> 
> Have the parent cluster registered itself as a child cluster?
> 
> > how can i check resources running status in each child clusters.
> 
> Currently there are two ways to get the status.
> 
> 1. For deployment/statefulset/job resources, you can visit `Subscription` status to get an aggregated status from each child clusters. Such as [Checking Aggregated Status](https://clusternet.io/docs/tutorials/multi-cluster-apps/aggregated-status/).
> 2. Also you can check them directly in child clusters from parent cluster.
> 
> ```shell
> $ kubectl clusternet --cluster-id=7dc5966e-6736-48dd-9a82-2e4d74d30443 \
>  --child-kubeconfig=./your-child-cluster-kubeconfig get ns
> ```

In child cluster, can i use command: kubectl get deploy -n foo, to check deployment status that i have create in parent cluster?

**Comment by dixudx** [comment]
> In child cluster, can i use command: kubectl get deploy -n foo, to check deployment status that i have create in parent cluster?

Sure.

**Comment by Sword-zhj** [comment]
> > In child cluster, can i use command: kubectl get deploy -n foo, to check deployment status that i have create in parent cluster?
> 
> Sure.

ok thank you very much

**Comment by Sword-zhj** [comment]
How to access child cluster services through parent cluster apiserver？

**Comment by dixudx** [comment]
> How to access child cluster services through parent cluster apiserver？

`kube-apiserver` does provider service proxy. Unless we can access child cluster from parent cluster, then we can access services running in child clusters.

Please refer to [access child cluster with curl](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-curl/). You can replace child cluster service url instead.

**Comment by dixudx** [comment]
@Sword-zhj You can follow below official wechat account of Clusternet.

![image](https://user-images.githubusercontent.com/5449021/184085916-fcc48ad3-6ab0-428a-b175-ca11d19a1645.png)

**Comment by Sword-zhj** [comment]
Whether the network between child clusters can connect with each other？ for example：child cluster a connect to child cluster b

**Comment by Sword-zhj** [comment]
> @Sword-zhj You can follow below official wechat account of Clusternet.
> 
> ![image](https://user-images.githubusercontent.com/5449021/184085916-fcc48ad3-6ab0-428a-b175-ca11d19a1645.png)

ok

**Comment by dixudx** [comment]
> Whether the network between child clusters can connect with each other？ for example：child cluster a connect to child cluster b

[Submariner](https://submariner.io/) could work as an add-on to help extend the cross-cluster networking.

**Comment by Sword-zhj** [comment]
> > Whether the network between child clusters can connect with each other？ for example：child cluster a connect to child cluster b
> 
> [Submariner](https://submariner.io/) could work as an add-on to help extend the cross-cluster networking.

thank you very much.
