### ISSUE TITLE
dry run support for managed cluster

### ISSUE THREAD

**Issue by snstaberah** [clusternet/clusternet#457]
#### What happened:
when i do a kubectl dry run command to the k8s cluster managed by clusternet ，there goes an error: dry run is not supported;     

I think  maybe this is a problem  caused by remote-dialer.clientDial.newConnect ? or rejected by aggregated apiserver ?  the response time is very short，such as 1ms/2ms，so it probably happened  in the clusternet-hub side；

Is there a plan to support dry-run method？

![image](https://user-images.githubusercontent.com/8952747/185557062-6a6abd8c-2cdd-4ccc-ac35-e0ac53742c45.png)

#### What you expected to happen:
user can use  dry run command  to cluster managed  by clusternet 
#### How to reproduce it (as minimally and precisely as possible):
1、register  a cluster by  deploy clusternet-agent；
2、make a proxy kubeconfig  to access  the cluster   through clusternet-hub；
3、 kubectl create  ns  test  --kubeconfig=proxyconfig  --dry-run=server -v=9

#### Environment:
- Clusternet version: v0.10

- Kubernetes version (use `kubectl version`): v1.20.10

**Comment by yeqiugt** [comment]
I had the same problem, and solved it with this https://github.com/yeqiugt/apiserver/commit/f256a01128ff7b68b84a829c25e4466bda1a3301, can i create a pr to fix it? @dixudx

**Comment by dixudx** [comment]
Sure. Please go ahead. @yeqiugt

**Comment by yeqiugt** [comment]
i create a pr https://github.com/clusternet/apiserver/pull/1 in clusternet/apiserver, and then, the go.mod in clusternet/clusternet also need to be edit

**Comment by dixudx** [comment]
@yeqiugt Please help bump `go.mod` in clusternet/clusternet.
