### ISSUE TITLE
How can I cross cluster connections over clusternet?

### ISSUE THREAD

**Issue by Sword-zhj** [clusternet/clusternet#458]
#### Reason for failure:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/32220271/185583964-5422a34b-98fd-404b-9745-a11247fd14f4.png">
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/32220271/185585205-e0ec5f1e-e4de-4569-9c29-67ebb2b1c4c2.png">

#### Anything else we need to know:
how should i do that access a svc created in clusternet-cluster-kwdmc from another cluster named clusternet-cluster-79256.  Is there any documentation？

**Comment by dixudx** [comment]
IIUC, you are asking how to access services running in child clusters. And these services are not exposed with any external load balancers or ingress routes.

@Sword-zhj You can construct a kubeconfig for your child cluster `clusternet-cluster-79256`. You can follow this guide [Visiting Child Clusters with Dedicated KubeConfig](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/construct-a-dedicated-kubeconfig/). Now with this kubeconfig, you could proxy child cluster to local. Also you may wanna to [try curl](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-curl/), which works the same way as kubeconfig. Such as,

```bash
kubectl proxy --kubeconfig=your-child-cluster-kubeconfig
```

Then you can use kubernetes built-in service proxy capabilities to [visit the services running in cluster](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#accessing-services-running-on-the-cluster). Such as

```
http://127.0.0.1:8001/api/v1/namespaces/my-ns/services/my-svc-name/proxy
```

**Comment by dixudx** [comment]
It seems if we have `kubectl clusternet port-forward`, this will be easier to visit services running in child clusters.

**Comment by dixudx** [comment]
Works with `kubectl clusternet` plugin v0.7.0.

Supposing we've got a nginx running in **child cluster**.

```bash
$ kubectl run nginx --image=nginx:1.23
pod/nginx created
```

Now we can use `port-forward` to visit locally by url `http://127.0.0.1:8080/`.

```bash
$ kubectl clusternet port-forward --cluster-id=20a3fe1d-4d25-4470-9bef-c0dd504b4c62 --child-kubeconfig=./child-kubeconfig -n default pod/nginx 8080:80
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
```

**Comment by dixudx** [comment]
docs will be updated in clusternet/website#37.
