### ISSUE TITLE
Ask for more detail document about deploy application to children-clusters

### ISSUE THREAD

**Issue by victory460** [clusternet/clusternet#464]
![image](https://user-images.githubusercontent.com/30213558/186936128-89b27e82-4e5d-4088-a183-78b28476d90d.png)

This ideal is awesome and perfect.

Can you describe more detail about that the flow process from accept yaml to scheduling and deployment applications to children-clusters?

Such as, How to deploy `Describtion` to children-clusters?  How to distribute `Subscription` to `Base`?

Give me some pointers idea and related code function about these, I will learn it. 

**Thanks a lot.**

**Comment by dixudx** [comment]
@victory460 Thanks for your interest.

Here is a [Chinese document](https://mp.weixin.qq.com/s?__biz=Mzg5NjA1MjkxNw==&mid=2247517235&idx=1&sn=3b876ee31352c5633384186bb6afd5fb&chksm=c0043fe9f773b6ff3932f1b506c2888df60374ff6cad02a36b44599650cad4c1a4355e331c4a&scene=21#wechat_redirect) that briefly talk about the application deployments.

And also you can learn these concepts from <https://clusternet.io/zh-cn/docs/concepts/>.

> Give me some pointers idea and related code function about these, I will learn it.

You can find all the controllers https://github.com/clusternet/clusternet/tree/main/pkg/controllers/apps. These controllers will reconcile specific objects and populate new objects. This is quite similar with deployment, replicaset controllers in Kubernetes.

**Comment by dixudx** [comment]
@victory460 Also you can try to search Wechat official account `Clusternet`, where you can receive some new articles and chart with me.

**Comment by victory460** [comment]
Thanks!

> @victory460 Also you can try to search Wechat official account `Clusternet`, where you can receive some new articles and chart with me.
