### ISSUE TITLE
Does clusternet support impersonate method  ?

### ISSUE THREAD

**Issue by yeqiugt** [clusternet/clusternet#488]
#### Why is this needed:
I use clusternet to manage muti-cluster, but when I use impersonate method to access child-cluster, I get an error; by reading the source code of clusternet, I think clusternet does not support impersonate method.
#### What would you like to be added:
If this is true, are there plans to support impersonate methods? i mean : `Impersonate-User`, `Impersonate-Group` , and `Impersonate-Extra-`

**Comment by dixudx** [comment]
Please try `clusternet-MY-EXTRA-HEADER`. In your case, you can specify `clusternet-Impersonate-User`.

**Comment by yeqiugt** [comment]
I add this header but it seems [impersonation ](impersonation ) doesn't work.

**Comment by dixudx** [comment]
@yeqiugt Would you please share your steps, commands, or error messages?

**Comment by yeqiugt** [comment]
> @yeqiugt Would you please share your steps, commands, or error messages?
1. Edit kubeconfig to add headers and user information
![image](https://user-images.githubusercontent.com/37202250/191904868-d32ce60c-cb99-4d93-9564-093072137d33.png)

2. Use this kubeconfig to access child-cluster, note that the header has been set correctly, and child-cluster returns the result
![image](https://user-images.githubusercontent.com/37202250/191905074-c1260708-cccd-4e6e-8d95-6120f2e7d578.png)

3. But in child-cluster, user `yeqiu` does not have right to list namespaces.
![image](https://user-images.githubusercontent.com/37202250/191905251-f05e7425-45b1-4b28-ad6a-4e82faf22f42.png)

4. I also tried setting the header `clusternet-Impersonate-User` directly, but the result is the same.
![image](https://user-images.githubusercontent.com/37202250/191906805-75d9b2e0-4438-4097-ae84-febdc289b7ca.png)

**Comment by dixudx** [comment]
@yeqiugt I see. Actually the header `clusternet-Impersonate-User` is passed directly to child cluster. But the desired behavior is passing `Impersonate-User`.
