### ISSUE TITLE
Parent cluster high availability problem

### ISSUE THREAD

**Issue by librant** [clusternet/clusternet#494]
For the parent cluster, is it supported to upgrade the child cluster to the parent cluster? If there is a problem with the api-server of the parent cluster, will it affect the normal function of the child cluster?

**Comment by dixudx** [comment]
> For the parent cluster, is it supported to upgrade the child cluster to the parent cluster?

A parent cluster can be a child cluster of itself as well. That means we can register the parent cluster to itself as a child cluster.

Theoretically, we can promote a child cluster to be a separate parent cluster.

> If there is a problem with the api-server of the parent cluster, will it affect the normal function of the child cluster?

No. All the resources are already deployed to each child cluster, thus the child cluster itself will help maintain the desired statuses of those resources.

**Comment by dixudx** [comment]
Close.
Please feel free to reopen it if necessary.
