### ISSUE TITLE
k3s v1.24.6+k3s1 child cluster working abnormally

### ISSUE THREAD

**Issue by jasine** [clusternet/clusternet#500]
#### What happened:

when I upgrade  k3s version from v1.23.8+k3s2 to v1.24.6+k3s1，helm release  failed syncing to child cluster

logs on clusternet-agent

```
W1009 13:05:24.374070       1 clusterstatus_controller.go:140] failed to discover service CIDR: can't get ServiceIPRange
W1009 13:05:24.383964       1 clusterstatus_controller.go:259] failed to list podMetris with err: 0x24da820
W1009 13:05:24.385094       1 clusterstatus_controller.go:283] failed to list nodeMetris with err: 0x24da820
E1009 13:05:26.203675       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
E1009 13:05:31.818574       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
E1009 13:05:38.021635       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
W1009 13:05:43.676526       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1alpha1.ServiceExport: serviceexports.multicluster.x-k8s.io is forbidden: User "system:serviceaccount:clusternet-system:clusternet-agent" cannot list resource "serviceexports" in API group "multicluster.x-k8s.io" at the cluster scope
E1009 13:05:43.676571       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ServiceExport: failed to list *v1alpha1.ServiceExport: serviceexports.multicluster.x-k8s.io is forbidden: User "system:serviceaccount:clusternet-system:clusternet-agent" cannot list resource "serviceexports" in API group "multicluster.x-k8s.io" at the cluster scope
W1009 13:05:44.392428       1 clusterstatus_controller.go:140] failed to discover service CIDR: can't get ServiceIPRange

```

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`): v0.12.0
    - Clusternet-hub version (user `clusternet-hub --version=json`): v0.12.0
- Kubernetes version (use `kubectl version`): v1.24.6+k3s1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0-126-generic

**Comment by dixudx** [comment]
> E1009 13:05:26.203675       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
E1009 13:05:31.818574       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
E1009 13:05:38.021635       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer

@jasine Please check in your child cluster to see whether this serviceaccount exists. This is part of the deployment of `clusternet-agent`.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusternet-app-deployer
  namespace: clusternet-system
```

**Comment by jasine** [comment]
> > E1009 13:05:26.203675       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
> > E1009 13:05:31.818574       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
> > E1009 13:05:38.021635       1 wait.go:188] no secrets found in ServiceAccount clusternet-system/clusternet-app-deployer
> 
> @jasine Please check in your child cluster to see whether this serviceaccount exists. This is part of the installation of `clusternet-agent`. It should be there.
> 
> ```yaml
> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   name: clusternet-app-deployer
>   namespace: clusternet-system
> ```

both clusternet-agent and  clusternet-app-deployer exist

**Comment by dixudx** [comment]
> when I upgrade k3s version from v1.23.8+k3s2 to v1.24.6+k3s1，helm release failed syncing to child cluster

Could you please share the upgrading steps?

**Comment by jasine** [comment]
> > when I upgrade k3s version from v1.23.8+k3s2 to v1.24.6+k3s1，helm release failed syncing to child cluster
> 
> Could you please share the upgrading steps?

Sorry, I misexpressed, I just upgrade to latest stable k3s version installing on new child cluster

**Comment by dixudx** [comment]
@jasine So this problem only happens on `v1.24.6+k3s1`, right?

**Comment by dixudx** [comment]
@jasine What's the version of Kubernetes where `clusternet-hub` is running?

**Comment by jasine** [comment]
@dixudx v1.22.7+k3s1 , so the parent cluster must upgrade to v1.24.6+k3s1 either?

**Comment by dixudx** [comment]
> @dixudx v1.22.7+k3s1 , so the parent cluster must upgrade to v1.24.6+k3s1 either?

Not really. I just want to narrow down the scope and find the root cause.

Now it seems to be related to the version of kube v1.24. Otherwise, new k3s server should work normally.
