### ISSUE TITLE
the example/scheduling-with-mcs-api doesn't work with kind

### ISSUE THREAD

**Issue by Airren** [clusternet/clusternet#508]
I created 4 clusters through the script in `hank/local-running.sh`, with different POD CIDR.

cluster images version: v0.12.0
               
```            
            Kind Docker IP       Pod CIDR 
Parent       192.169.0.2              10.244.0.1/24
Child1       192.169.0.4              10.244.1.1/24
Child2       192.169.0.5              10.244.2.1/24
Child3       192.169.0.6              10.244.3.1/24

```
After ` kubectl clutsetnet apply -f examples/scheduling-with-mcs-api/scheduling` and `kubectl apply -f  service-import.yaml`.  As is shown in the picture,  a service created and there are the related `endpointslices`.

![image](https://user-images.githubusercontent.com/14846116/196209338-30a6262d-ffd7-4ac1-b42d-418fb9f0a057.png)

But, I try to test the service on the Parent Cluster Host as follows, It doesn't work. And, in the iptables, It shows no endpoints.
![image](https://user-images.githubusercontent.com/14846116/196210892-fa1b6fa6-ad52-47d3-864e-50baffd6bad2.png)

Question:
1. Should I add routes on the Parent-Cluster host to the ChildClusters Pod CIDR? Such as `ip route add 10.244.1.0/24 via 192.169.0.4 dev eth0 `.
2. How to make the service work? Should it need to create a corresponding endpoint for this service?

More information:
Service details
![image](https://user-images.githubusercontent.com/14846116/196212442-5eb27e3b-a893-400e-b04f-d056f0ff659f.png)
Service Import Details
![image](https://user-images.githubusercontent.com/14846116/196212648-be6b7f90-1e7d-45e0-94d7-92c034d9602f.png)

What's more:
There is a mistake in the document on this [page]( https://clusternet.io/docs/tutorials/mutil-cluster-service/visting-services-in-child-cluster/). The path `examples/scheduling-with-service-expose/service-import.yaml` does not exist in the repo.
![image](https://user-images.githubusercontent.com/14846116/196213276-002adfe0-bce8-47d3-894d-e1000c483c39.png)

**Comment by dixudx** [comment]
@lmxia Please help verify the issue. Thanks.

**Comment by lmxia** [comment]
1. > Should I add routes on the Parent-Cluster host to the ChildClusters Pod CIDR? Such as ip route add 10.244.1.0/24 via 192.169.0.4 dev eth0 .

Yes, mcs works on the premise that pods in child clusters can be reachable.

2.  > How to make the service work? Should it need to create a corresponding endpoint for this service

No, no need to create endpoints.

**Comment by Airren** [comment]
Thanks for your answer.
