### ISSUE TITLE
clusternet schduler support SchdulerExtender to extend?

### ISSUE THREAD

**Issue by victory460** [clusternet/clusternet#509]
**clusternet schduler** support `SchdulerExtender` to extend?

**Comment by dixudx** [comment]
> **clusternet schduler** support `SchdulerExtender` to extend?

No. And I don't suggest using extender to extend scheduler.

Clusternet scheduler is using scheduling framework, which uses plugins to implement different scheduling phases. And it is easy to hook your out-of-tree plugins.

**Comment by dixudx** [comment]
> If want to update the logic code of score plugin , have a way to hot update the plugin but no restart clusternet schduler？

No. For scheduling framework, you need to rebuild scheduler and update it.

Scheduler extender is also not suggested by Kubernetes community.

**Comment by victory460** [comment]
> > If want to update the logic code of score plugin , have a way to hot update the plugin but no restart clusternet schduler？
> 
> No. For scheduling framework, you need to rebuild scheduler and update it.
> 
> Scheduler extender is also not suggested by Kubernetes community.

OK. Thanks a lot.
