### ISSUE TITLE
informer waits for nonexistent v1.EndpointSlice in k8s v1.18

### ISSUE THREAD

**Issue by dixudx** [clusternet/clusternet#515]
#### What happened:
kind/bug

`clusternet-hub` v0.12.0 is not working as expected for k8s v1.18.

In Clusternet v0.12.0, `mcs-api` was introduced and used `discovery/v1 EndpointSlice`, which was not existed for k8s with lower version than v1.20.x.

```
I1101 06:38:40.580770       1 reflector.go:255] Listing and watching *v1.EndpointSlice from pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167
W1101 06:38:40.581532       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1.EndpointSlice: the server could not find the requested resource
E1101 06:38:40.581547       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: the server could not find the requested resource
```

#### Anything else we need to know?:

> **Only affects Kubernetes lower than v1.20.0**

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`): v0.12.0
    - Clusternet-hub version (user `clusternet-hub --version=json`): v0.12.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
cc @metang326 @lmxia

**Comment by metang326** [comment]
> cc @metang326 @lmxia
