### ISSUE TITLE
abnormal manifests deletion when agent runs in parent cluster

### ISSUE THREAD

**Issue by dixudx** [clusternet/clusternet#528]
#### What happened:
kind/bug

When `clusternet-agent` runs in parent cluster, if we delete a `Subscription`, then corresponding manifest feeds are deleted as well.

This only happens when `clusternet-agent` runs in parent cluster.

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by silenceper** [comment]
What is the reason for this?

**Comment by dixudx** [comment]
> What is the reason for this?

We're still investigating this. It is a weird bug. Feel free to work on this if you've got any clues.

**Comment by lmxia** [comment]
This issue has been fixed.
