### ISSUE TITLE
clusternet-hub failed to get leader elected in k8s 1.25

### ISSUE THREAD

**Issue by Sad-polar-bear** [clusternet/clusternet#531]
#### What happened:
kind/bug

Testing with all commit id and in some commit clusternet-hub can not leaderelection successful.

![image](https://user-images.githubusercontent.com/28644213/200496203-ec3160b0-f5db-496a-bb55-f52ccb00ae81.png)

#### What you expected to happen:
          
![image](https://user-images.githubusercontent.com/28644213/200496295-ca263978-45a6-4297-8848-1f6c8d4f31dd.png)

#### How to reproduce it (as minimally and precisely as possible):
          using commit id: d0ca5ebbb91753a2914d137b80c26e88e90465d4

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
   v1.25.3

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
Starting from v1.25, Kubernetes stops serving `EndpointSlice` with `v1beta1`.

> I1108 15:14:41.370101   15517 reflector.go:255] Listing and watching *v1beta1.EndpointSlice from pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167
>W1108 15:14:41.466188   15517 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: failed to list *v1beta1.EndpointSlice: the server could not find the requested resource
>E1108 15:14:41.466230   15517 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1beta1.EndpointSlice: failed to list *v1beta1.EndpointSlice: the server could not find the requested resource

In #518, `discovery/v1` is replaced by `discovery/v1beta1` to be compatible with k8s v1.18.

cc @metang326 @mars1024
