### ISSUE TITLE
description cannot be deleted when syncMode is `Pull` and `Recovery` feature is enabled

### ISSUE THREAD

**Issue by silenceper** [clusternet/clusternet#541]
#### What happened:
description cannot be deleted when syncMode is `Pull` and `Recovery` feature is enabled.

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
cc @lmxia
