### ISSUE TITLE
What is the difference with kubefed, why not use kubefed?

### ISSUE THREAD

**Issue by laik** [clusternet/clusternet#55]
as title

**Comment by dixudx** [comment]
> What is the difference with kubefed, why not use kubefed

@laik First of all, Clusternet don't need to create such a `FederatedAbc` CRD. Kubefed users need to declare `FederatedAbc` CRDs one by one with `kubefedctl`. Moreover, currently ***kubefed community is in slow development***. Clusternet supports users use native way to distribute resources to multiple clusters without noticing fed resources. **With Clusternet, distributing resources to multiple clusters are as simple as applying resources to a single cluster.**

Besides that, **Clusternet supports full-fledged cluster managements**, including automatic cluster registrations, visiting child clusters with RBAC, various cluster topologies (such as running in public cloud, private cloud, edge cloud, etc), etc. However kubefed is not that full-fledged, which only supports registering cluster manually by `kubefedctl join`.
