### ISSUE TITLE
replace crds before upgrade helm charts

### ISSUE THREAD

**Issue by jasine** [clusternet/clusternet#559]
#### What would you like to be added:

replace crds before upgrade helm charts

#### Why is this needed:

due to the design of helm, crds will not upgrade when chart upgrade, that will cause conflict and `helmrelease` status  `falied`, for example 

```
 Warning  FailedSynced  26s (x18 over 25m)  clusternet-hub    unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "hostNetwork" in com.coreos.monitoring.v1.Prometheus.spec
```

helm community provided a workaround is execute `kubectl replace -f ./crds`

**Comment by dixudx** [comment]
> helm community provided a workaround is execute `kubectl replace -f ./crds`

@jasine I wonder whether we could mitigate this issue by pre-applying these CRDs via `Subscription` before we upgrade the chart.

**Comment by dixudx** [comment]
@jasine I took a look on the helm charts handling. And the issue could be mitigated on Clusternet side.

`Chart` does provide a function `CRD`, which can be used to pre-apply to child clusters before upgrading the chart.

https://github.com/helm/helm/blob/ced54b12896ae933017782e2bbd722e2bc8c0914/pkg/chart/chart.go#L136-L151

**Comment by jasine** [comment]
@dixudx ok, I will try to implement this feature later
