### ISSUE TITLE
Where can I find relevant information about  `cross-cluster canary rollout`?

### ISSUE THREAD

**Issue by machine3** [clusternet/clusternet#571]

**Comment by dixudx** [comment]
@machine3 With the help of `Localization`, we can rollout the instances with newer configuration in specific cluster. Learn [How to Set Overrides in Clusternet](https://clusternet.io/docs/tutorials/multi-cluster-apps/setting-overrides/). After the updated instances work as desired, we can apply the newer configuration to a group of clusters using `Globalization`, or directly update the `Manifest` feeds, which would apply to all matching clusters.

**Comment by dixudx** [comment]
Close.
Please feel free to reopen it if necessary.
