### ISSUE TITLE
Refactor Controllers out from Clusternet-Hub into a New Clusternet-Controller-Manager

### ISSUE THREAD

**Issue by lmxia** [clusternet/clusternet#590]
#### What would you like to be added:
Move all controllers out from clusternet-hub into a new component named "clusternet-controller-manager". Leave shadow-API-server alone in clusternet-hub.

#### Why is this needed:
Api-server and controllers are logic independent, we will make api-server less coupled with controllers, by separating the two parts.

- [x] #638
- [x] #646
- [x] #647
- [x] #648 
- [x] #589 
- [x] clusternet/charts#41
- [x] clusternet/website#74

**Comment by dixudx** [comment]
Glad to see this happen. This refactoring brings in multiple benefits and improves the performance of `clusternet-hub`. Nice feature.

**Comment by dixudx** [comment]
@lmxia Any progress on this feature? Shall we break down into a set of small tasks?

**Comment by lmxia** [comment]
> @lmxia Any progress on this feature? Shall we break down into a set of small tasks?
Sure, it's much better to break down into small tasks.

**Comment by dixudx** [comment]
All done.
