### ISSUE TITLE
support enable pprof

### ISSUE THREAD

**Issue by silenceper** [clusternet/clusternet#614]
#### Why is this needed:
for Profiling

**Comment by dixudx** [comment]
@silenceper Already supported in #606 and #608. Will be available in v0.15.0.

**Comment by silenceper** [comment]
does clusternet-hub support ?

**Comment by dixudx** [comment]
> does clusternet-hub support ?

@silenceper Sure. That has been already supported in `clusternet-hub` since the beginning.

**Comment by dixudx** [comment]
/close

Please feel free to reopen it if necessary.
