### ISSUE TITLE
support atomic param to be set separately during install helmrelease and upgrade helmrelease

### ISSUE THREAD

**Issue by wl-chen** [clusternet/clusternet#625]
#### What would you like to be added:
support atomic param to be set separately during install and upgrade

#### Why is this needed:
Currently, the atomic parameter applies uniformly to the installation and upgrade process, which is not very flexible. It is hoped that the atomic param during install and the atomic param during upgrade can be set separately. This can support scenarios where the values to be set for atomic are different between install and upgrade.

**Comment by dixudx** [comment]
@wl-chen Please feel free to make your changes via a Pull Request.

> Currently, the atomic parameter applies uniformly to the installation and upgrade process, which is not very flexible.

Any suggestions on this kind of change?

**Comment by wl-chen** [comment]
> 



> @wl-chen Please feel free to make your changes via a Pull Request.
> 
> > Currently, the atomic parameter applies uniformly to the installation and upgrade process, which is not very flexible.
> 
> Any suggestions on this kind of change?

add an additional upgrade atomic param in helmchart cr？

**Comment by dixudx** [comment]
> Currently, the atomic parameter applies uniformly to the installation and upgrade process, which is not very flexible.

> add an additional upgrade atomic param in helmchart cr？

@wl-chen I'm ok with this change. Please help submit a PR on this. Thanks.

cc @DanielXLee FYI.
