### ISSUE TITLE
the names of auto-generated objects may exceed the length limit

### ISSUE THREAD

**Issue by dixudx** [clusternet/clusternet#645]
```go
desc.Name = fmt.Sprintf("%s-generic", base.Name)
```

or

```go
loc.Name = fmt.Sprintf("%s-%s-%s", base.Name, strings.ToLower(feedOrder.Feed.Kind), suffixName)
```

_Originally posted by @yinsenyan in https://github.com/clusternet/clusternet/pull/642#discussion_r1152812350_

**Comment by yinsenyan** [comment]
Use uid: kind as much as possible
use list instead of get whenever possible.

**Comment by yinsenyan** [comment]
With #681 , `Base` name is `sub.Namespace` and `sub.Name`, and used for `Descriptions` label value

```
known.ConfigNameLabel:      base.Name,
```
In k8s document, label value length less then 63 , is most likely to cause problem.
[doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

**Comment by yinsenyan** [comment]
Perhaps we can thoroughly solve this problem through some means.

All auto-generated objects In clusternet include base , description, localization , globalization.
Now, base name is subscription name or subscription name+namespace, description name is base name + `-generic`, and localization(for schedule result) name is base.name + feed.kind + feed.namespace+feed.name, so panic.

So, this auto-generated objects name should use sub.name + suffix , suffix is a random string of 5 or 9 characters, just like deployment and replicaset name.

If use random string suffix, all of get object need change to list , just like [here](https://github.com/clusternet/clusternet/blob/main/pkg/controllermanager/deployer/deployer.go#L423)
```
	oldNameBase, err := deployer.baseLister.Bases(baseTemplate.Namespace).Get(baseTemplate.Name)
	if err == nil {
		// get old name base, update it
		return deployer.updateBase(context.TODO(), sub, baseTemplate, oldNameBase)
	}
```

**Comment by dixudx** [comment]
> all auto-generated objects name should use sub.name + suffix , suffix is a random string of 5 or 9 characters, just like deployment and replicaset name.

This sounds good to me. I'd prefer to have a shorter suffix, e.g. 5 characters as a rule.
