### ISSUE TITLE
cannot deploy demo application, hub and agent have some error logs

### ISSUE THREAD

**Issue by xjbdjay** [clusternet/clusternet#656]
#### What happened:

I use `hack/local-running.sh` to create one parent cluster and three child clusters. But I cannot deploy demo application, there is nothing happened.

#### What you expected to happen:

the demo application is here. https://clusternet.io/docs/tutorials/multi-cluster-apps/static-weight-scheduling-to-multiple-clusters/

#### Anything else we need to know?:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/3378368/230590438-e18bfa01-2e44-41d9-bd17-368cd996c6ed.png">
hub log:

```
E0407 10:06:21.997221       1 timeout.go:137] post-timeout activity - time-elapsed: 17.427557ms, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:06:21.998314       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0407 10:06:21.999414       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0407 10:06:22.001672       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0407 10:06:22.005035       1 timeout.go:137] post-timeout activity - time-elapsed: 25.138282ms, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:06:22.006205       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0407 10:06:22.007437       1 timeout.go:137] post-timeout activity - time-elapsed: 27.623114ms, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:06:22.009702       1 timeout.go:137] post-timeout activity - time-elapsed: 23.611897ms, GET "/apis/shadow/v1alpha1" result: <nil>
I0407 10:06:28.012398       1 clusterlifecycle_controller.go:183] successfully synced ManagedCluster "clusternet-ddtff/child3"
E0407 10:06:51.959470       1 writers.go:117] apiserver was unable to write a JSON response: http2: stream closed
E0407 10:06:51.959649       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0407 10:06:51.959485       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="4a0a9da2-d0af-47a7-99ba-98ae71cb4bf4"
E0407 10:06:51.960302       1 writers.go:117] apiserver was unable to write a JSON response: http2: stream closed
E0407 10:06:51.960342       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="8c1a112c-a2fa-4765-a604-67da95f54c2f"
E0407 10:06:51.961522       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0407 10:06:51.963766       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0407 10:06:51.964932       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0407 10:06:51.967382       1 timeout.go:137] post-timeout activity - time-elapsed: 7.873812ms, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:06:51.968525       1 timeout.go:137] post-timeout activity - time-elapsed: 8.161733ms, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:07:51.919466       1 writers.go:117] apiserver was unable to write a JSON response: http2: stream closed
E0407 10:07:51.919868       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0407 10:07:51.919491       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="6adf66e4-9bc2-4815-bc23-b0c13a5b0f61"
E0407 10:07:51.921087       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0407 10:07:51.922767       1 timeout.go:137] post-timeout activity - time-elapsed: 3.255671ms, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:08:21.899221       1 writers.go:117] apiserver was unable to write a JSON response: http2: stream closed
E0407 10:08:21.899284       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0407 10:08:21.899368       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="510768a7-9304-4849-8328-57cd5c3842f0"
E0407 10:08:21.901131       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0407 10:08:21.902359       1 timeout.go:137] post-timeout activity - time-elapsed: 2.954368ms, GET "/apis/shadow/v1alpha1" result: <nil>
I0407 10:08:22.681682       1 clusterlifecycle_controller.go:183] successfully synced ManagedCluster "clusternet-d2hwb/child1"
I0407 10:08:50.957995       1 clusterlifecycle_controller.go:183] successfully synced ManagedCluster "clusternet-hvkhf/child2"
E0407 10:08:51.879376       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="9b0af31b-0adf-40b6-88a9-77226401a375"
E0407 10:08:51.879398       1 timeout.go:137] post-timeout activity - time-elapsed: 1.618µs, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:08:58.078371       1 feedinventory.go:293] error syncing 'default/static-dividing-scheduling-demo': [Deployment "my-nginx" not found, Service "my-nginx-svc" not found, Namespace "bar" not found], requeuing
E0407 10:09:21.859231       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="2b992112-9a89-4c2c-af2c-9f7470ad38bf"
E0407 10:09:21.859294       1 writers.go:117] apiserver was unable to write a JSON response: http2: stream closed
E0407 10:09:21.859740       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="f109f67a-8fbe-4cb5-86ce-2ed30f792a40"
E0407 10:09:21.859786       1 timeout.go:137] post-timeout activity - time-elapsed: 2.166µs, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:09:21.859805       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="c8af7241-13dd-442b-8a78-2b30c4a24156"
E0407 10:09:21.859814       1 timeout.go:137] post-timeout activity - time-elapsed: 645ns, GET "/apis/shadow/v1alpha1" result: <nil>
E0407 10:09:21.860995       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0407 10:09:21.863096       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0407 10:09:21.868708       1 timeout.go:137] post-timeout activity - time-elapsed: 9.416726ms, GET "/apis/shadow/v1alpha1" result: <nil>
I0407 10:09:27.896659       1 clusterlifecycle_controller.go:183] successfully synced ManagedCluster "clusternet-ddtff/child3"
```

agent log:

```
0407 09:35:11.384574       1 leaderelection.go:258] successfully acquired lease clusternet-system/self-cluster                                                                                                                                                      [180/11513]
I0407 09:35:11.384731       1 agent.go:292] start registering current cluster as a child cluster...
I0407 09:35:11.384759       1 agent.go:302] retrieving cluster id
I0407 09:35:11.401726       1 agent.go:307] current cluster id is "4bc33b4e-02ae-4c38-bd30-e902bc7725ea"
I0407 09:35:11.405142       1 agent.go:365] try to bootstrap cluster registration if needed
I0407 09:35:11.416179       1 agent.go:386] successfully create ClusterRegistrationRequest "clusternet-4bc33b4e-02ae-4c38-bd30-e902bc7725ea"
I0407 09:35:17.327583       1 agent.go:437] the registration request for cluster "4bc33b4e-02ae-4c38-bd30-e902bc7725ea" gets approved
I0407 09:35:17.334727       1 agent.go:249] featuregate SocketConnection is enabled, preparing setting up socket connection...
I0407 09:35:17.335037       1 server.go:129] Starting clusternet predictor
I0407 09:35:17.335091       1 status_manager.go:80] starting status manager to report heartbeats...
I0407 09:35:17.335174       1 deployer.go:75] starting deployer ...
I0407 09:35:17.335290       1 shared_informer.go:240] Waiting for caches to sync for cluster-status-controller
I0407 09:35:17.335301       1 shared_informer.go:247] Caches are synced for cluster-status-controller
time="2023-04-07T09:35:17Z" level=info msg="Connecting to proxy" url="wss://172.18.0.2:6443/apis/proxies.clusternet.io/v1alpha1/sockets/4bc33b4e-02ae-4c38-bd30-e902bc7725ea"
I0407 09:35:17.336008       1 yacht.go:230] starting controller serviceexport
I0407 09:35:17.336031       1 shared_informer.go:240] Waiting for caches to sync for serviceexport
W0407 09:35:17.343855       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:35:17.344637       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
I0407 09:35:17.348849       1 deployer.go:108] sending events to parent apiserver
I0407 09:35:17.349288       1 helm.go:94] starting helm deployer...
I0407 09:35:17.349344       1 shared_informer.go:240] Waiting for caches to sync for helm-deployer
I0407 09:35:17.349359       1 generic.go:111] starting generic deployer...
I0407 09:35:17.349362       1 shared_informer.go:240] Waiting for caches to sync for generic-deployer
I0407 09:35:17.436545       1 shared_informer.go:247] Caches are synced for serviceexport
I0407 09:35:17.449807       1 shared_informer.go:247] Caches are synced for generic-deployer
I0407 09:35:17.449849       1 description.go:115] starting description controller...
I0407 09:35:17.449855       1 shared_informer.go:240] Waiting for caches to sync for description-controller
I0407 09:35:17.449852       1 shared_informer.go:247] Caches are synced for helm-deployer
I0407 09:35:17.449866       1 shared_informer.go:247] Caches are synced for description-controller
I0407 09:35:17.449873       1 helmrelease.go:99] starting helmRelease controller...
I0407 09:35:17.449878       1 shared_informer.go:240] Waiting for caches to sync for helmrelease-controller
I0407 09:35:17.449884       1 shared_informer.go:247] Caches are synced for helmrelease-controller
W0407 09:35:37.351053       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:35:37.351744       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:35:57.339257       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:35:57.340165       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:36:17.325817       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:36:17.326530       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:36:37.335375       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:36:37.336139       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:36:57.325014       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:36:57.325698       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:37:17.311685       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:37:17.312840       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:37:37.322916       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:37:37.323717       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:37:57.311995       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:37:57.312822       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:38:17.300320       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:38:17.301108       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:38:37.310763       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:38:37.311350       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:38:57.297509       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:38:57.298148       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
W0407 09:39:17.286082       1 clusterstatus_controller.go:262] failed to list podMetris with err: 0x2462280
W0407 09:39:17.286627       1 clusterstatus_controller.go:286] failed to list nodeMetris with err: 0x2462280
```

#### Environment:
- Clusternet version: v0.14
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration:  kind 
- OS (e.g: `cat /etc/os-release`):macos
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
> E0407 10:08:51.879398       1 timeout.go:137] post-timeout activity - time-elapsed: 1.618µs, GET "/apis/shadow/v1alpha1" result: <nil>
> E0407 10:08:58.078371       1 feedinventory.go:293] error syncing 'default/static-dividing-scheduling-demo': [Deployment "my-nginx" not found, Service "my-nginx-svc" not found, Namespace "bar" not found], requeuing

How would you apply the resources? Please use `kubectl clusternet apply`.

**Comment by xjbdjay** [comment]
yes, use 'kubectl clusternet apply.'

**Comment by xjbdjay** [comment]
> > E0407 10:08:51.879398       1 timeout.go:137] post-timeout activity - time-elapsed: 1.618µs, GET "/apis/shadow/v1alpha1" result: 
> > E0407 10:08:58.078371       1 feedinventory.go:293] error syncing 'default/static-dividing-scheduling-demo': [Deployment "my-nginx" not found, Service "my-nginx-svc" not found, Namespace "bar" not found], requeuing
> 
> How would you apply the resources? Please use `kubectl clusternet apply`.

**Comment by xjbdjay** [comment]
> > E0407 10:08:51.879398       1 timeout.go:137] post-timeout activity - time-elapsed: 1.618µs, GET "/apis/shadow/v1alpha1" result: 
> > E0407 10:08:58.078371       1 feedinventory.go:293] error syncing 'default/static-dividing-scheduling-demo': [Deployment "my-nginx" not found, Service "my-nginx-svc" not found, Namespace "bar" not found], requeuing
> 
> How would you apply the resources? Please use `kubectl clusternet apply`.


yes, used 'kubectl clusternet apply'

**Comment by dixudx** [comment]
@xjbdjay Please help verify below parts.

1. Make sure that all Clusternet components are running correctly. `kubectl get pod -n clusternet-system`.
2. Install `kubectl clusternet` plugin.

    ```bash
    kubectl clusternet get ns
    ```

    Above command should work correctly.

3. Make sure you've updated the `spec.subscribers.clusterAffinity.matchLabels`. Do remember to update the cluster-id to yours.

    ```yaml
      subscribers: # defines the clusters to be distributed to
        - clusterAffinity:
            matchLabels:
              clusters.clusternet.io/cluster-id: dc91021d-2361-4f6d-a404-7c33b9e01118 # PLEASE UPDATE THIS CLUSTER-ID TO YOURS!!!
    ```

4. Do remember to apply the resources using `kubectl clusternet apply`.

**Comment by dixudx** [comment]
#658 installed the missing component `clusternet-controller-manager` if you're using Clusternet v0.15.0.

**Comment by xjbdjay** [comment]
> 3\. yours

modified the cluster id .
<img width="721" alt="image" src="https://user-images.githubusercontent.com/3378368/230599999-8e47eec1-6568-4ea4-85ab-029fdac05425.png">

**Comment by xjbdjay** [comment]
> #658 installed the missing component `clusternet-controller-manager` if you're using Clusternet v0.15.0.

it's v0.14.0

**Comment by xjbdjay** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/3378368/230600384-32819220-5e8f-44e5-8333-a534c8486f89.png">
there is no deployment in child cluster too.

**Comment by dixudx** [comment]
Please describe the event messages.

```bash
kubectl get base -A
kubectl get desc -A
kubectl describe desc -n clusternet-xxx sub-xxx
```

**Comment by xjbdjay** [comment]
> Please describe the event messages.
> 
> ```shell
> kubectl get base -A
> kubectl get desc -A
> kubectl describe desc -n clusternet-xxx sub-xxx
> ```

<img width="293" alt="image" src="https://user-images.githubusercontent.com/3378368/230601116-e32555e6-0b84-485e-a4cb-df6ee871e384.png">

<img width="266" alt="image" src="https://user-images.githubusercontent.com/3378368/230601127-1c6af5a4-122f-46ba-a6df-72cf1e6b2aea.png">

**Comment by dixudx** [comment]
Then describe the event messages to get the scheduling info. Please replace with the right namespace and name of your subscription.

```bash
kubectl describe subxxxx -n abcxxx
```

**Comment by dixudx** [comment]
If `Base` and `Description` are not shown up, then the problem stays in the scheduling part. Maybe the right scheduling strategy, such as unmatched clusters.

**Comment by xjbdjay** [comment]
> Then describe the event messages to get the scheduling info. Please replace with the right namespace and name of your subscription.
> 
> ```shell
> kubectl describe subxxxx -n abcxxx
> ```
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/3378368/230601596-6420d8ed-4f7d-4761-aae2-0bbb05244ad1.png">

**Comment by xjbdjay** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/3378368/230602128-aff749eb-d594-4ecd-a4ea-dd58994d48ed.png">

**Comment by xjbdjay** [comment]
> If `Base` and `Description` are not shown up, then the problem stays in the scheduling part. Maybe the right scheduling strategy, such as unmatched clusters.

the cluster id is right

**Comment by xjbdjay** [comment]
> From the result of `kubectl describe sub xx -n xxx`, the resources are not found.
> 
> @xjbdjay Could you try to run `kubectl clusternet get deploy -n bar`. See what happens. Do remember to invoke the kubectl plugin `clusternet`!!!

<img width="421" alt="image" src="https://user-images.githubusercontent.com/3378368/230810676-afd91809-0b71-46d8-824b-05a6e6eadbb9.png">

**Comment by dixudx** [comment]
Any other steps that I can follow to reproduce your issue? Thanks.

**Comment by xjbdjay** [comment]
> Any other steps that I can follow to reproduce your issue? Thanks.

I just follow your tutorial. Use clusternet/hack/local-running.sh to create clusters in macos, and Deploy the example `clusternet/examples/static-dividing-scheduling`. 
I have a doubt that the hub and agent exist many error logs which confuse me.

**Comment by xjbdjay** [comment]
I retry this flow again. It succeeds. However, the deploy status is not right?
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/3378368/230819064-bcb93776-2158-49c0-b5e9-3a24a5c34471.png">

**Comment by dixudx** [comment]
> However, the deploy status is not right?

Not really. The deployments listing by `kubectl clusternet get deploy -n some-ns` are actually treated as templates. The templates can be used by other subscriptions as well. So we don't directly update statuses to these templates. Instead, such aggregated statuses will be updated to each subscription object.

You can follow guide on [checking aggregated status from child clusters](https://clusternet.io/docs/tutorials/multi-cluster-apps/aggregated-status/).

**Comment by xjbdjay** [comment]
I tried the second demo. It does't have any events and not scheduled to child clusters.
How long it takes to deploy the child clusters normally?
<img width="594" alt="image" src="https://user-images.githubusercontent.com/3378368/230821303-b7fb3da0-77b0-4cf7-b7d7-38d6106c65ad.png">

<img width="471" alt="image" src="https://user-images.githubusercontent.com/3378368/230821248-5628eec1-d015-49a5-b154-96388342dd26.png">

**Comment by dixudx** [comment]
> How long it takes to deploy the child clusters normally?

In a second.

> It does't have any events and not scheduled to child clusters.

Please find some clues from the logs of `clusternet-scheduler`, `clusternet-hub`.

**Comment by xjbdjay** [comment]
> 

It took too long to get effective events. I don't know what happened. Now there are some err logs.
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/3378368/230838540-4838b456-0f97-4a5e-ac18-11c6b8a3a469.png">

**Comment by dixudx** [comment]
From the scheduler log, it took a long time (from 03:27:42 to 04:20:57) to get the lease, which was quite abnormal. Here there were three leader elections and they should be invoked at very near time. However they were actually invoked with respectively timestamps at 03:27:51, 02:53:44 and 03:27:42. This was suspicious. It seemed that each of them was using different system time. This maybe a NTP issue.

Here I would suggest to [install Clusternet with more standard ways](https://clusternet.io/docs/installation/).

**Comment by xjbdjay** [comment]
The 4 clusters created by your scripts run in local macos, the same docker environment.

**Comment by xjbdjay** [comment]
> ```shell
> kubectl get base -A
> ```

I recreate the clusters using the updated local-running.sh. The issue still exists.
<img width="595" alt="image" src="https://user-images.githubusercontent.com/3378368/231395280-b14e7daf-0f87-46cb-b4ae-9fc094a586c2.png">

<img width="1587" alt="image" src="https://user-images.githubusercontent.com/3378368/231395074-0b8126d8-f02d-4372-ae4b-d6937e9b4673.png">

<img width="1774" alt="image" src="https://user-images.githubusercontent.com/3378368/231394957-21242344-3a4b-4da6-baa8-87a52854af60.png">

**Comment by dixudx** [comment]
> > ```shell
> > kubectl get base -A
> > ```
> 
> I recreate the clusters using the updated local-running.sh. The issue still exists. <img alt="image" width="595" src="https://user-images.githubusercontent.com/3378368/231395280-b14e7daf-0f87-46cb-b4ae-9fc094a586c2.png">
> 
> <img alt="image" width="1587" src="https://user-images.githubusercontent.com/3378368/231395074-0b8126d8-f02d-4372-ae4b-d6937e9b4673.png">
> 

@xjbdjay Please run with command `kubectl clusternet apply -f examples/dynamic-dividing-scheduling`!!!

Do NOT run with `kubectl apply -f examples/dynamic-dividing-scheduling`. We use `kubectl clusternet`. Please follow guide on [installing kubectl clusternet plugin](https://clusternet.io/docs/kubectl-clusternet/).

Remember to run with command `kubectl clusternet apply -f examples/dynamic-dividing-scheduling`. Thanks.

**Comment by xjbdjay** [comment]
> > > ```shell
> > > kubectl get base -A
> > > ```
> > 
> > 
> > I recreate the clusters using the updated local-running.sh. The issue still exists. <img alt="image" width="595" src="https://user-images.githubusercontent.com/3378368/231395280-b14e7daf-0f87-46cb-b4ae-9fc094a586c2.png">
> > <img alt="image" width="1587" src="https://user-images.githubusercontent.com/3378368/231395074-0b8126d8-f02d-4372-ae4b-d6937e9b4673.png">
> 
> @xjbdjay Please run with command `kubectl clusternet apply -f examples/dynamic-dividing-scheduling`!!!
> 
> Do NOT run with `kubectl apply -f examples/dynamic-dividing-scheduling`. We use `kubectl clusternet`. Please follow guide on [installing kubectl clusternet plugin](https://clusternet.io/docs/kubectl-clusternet/).
> 
> Remember to run with command `kubectl clusternet apply -f examples/dynamic-dividing-scheduling`. Thanks.

Thx. It's ok now.  The command is confusing since some commands need clusternet and some do not need.

**Comment by xjbdjay** [comment]
Another question: May i use one cluster to simulate parent cluster and child cluster?

**Comment by dixudx** [comment]
> The command is confusing since some commands need clusternet and some do not need.

You can always use `kubectl clusternet` for all the operations.

> May i use one cluster to simulate parent cluster and child cluster?

I am not sure that I get what you mean.

In Clusternet, a parent cluster can be a child cluster, which means we can manage all the clusters including parent cluster in a consistent behavior.

**Comment by xjbdjay** [comment]
@dixudx 
Agent crashed since invalid bootstrap token. However, I used the service account token not bootstrap token. It check the bootstrap token format failed.
<img width="1832" alt="image" src="https://user-images.githubusercontent.com/3378368/231640944-cd5ad968-8a2b-4e88-9149-b9e3b9bfc244.png">
<img width="792" alt="image" src="https://user-images.githubusercontent.com/3378368/231641334-db462f81-354d-4876-adb6-1458cacd0e1d.png">

**Comment by dixudx** [comment]
Move the discussion on token issue to #665.
