### ISSUE TITLE
clusternet-agent should use PATCH not UPDATE when doing ApplyResource

### ISSUE THREAD

**Issue by abstractmj** [clusternet/clusternet#662]
clusternet-agent ApplyResource  behavior needs to be like "kubectl apply" not "kubectl replace"

https://github.com/clusternet/clusternet/blob/9f150cc04e79c57b5ceee367b72f5dfff7ab5757/pkg/utils/deployer.go#L517

**Comment by dixudx** [comment]
> clusternet-agent ApplyResource behavior needs to be like "kubectl apply" not "kubectl replace"

Sounds good to me.
