### ISSUE TITLE
clusternet-agent crashed when using serviceaccount token for bootstrapping

### ISSUE THREAD

**Issue by dixudx** [clusternet/clusternet#665]
> Agent crashed since invalid bootstrap token. However, I used the service account token not bootstrap token. It check the bootstrap token format failed.
<img width="1832" alt="image" src="https://user-images.githubusercontent.com/3378368/231640944-cd5ad968-8a2b-4e88-9149-b9e3b9bfc244.png">
<img width="792" alt="image" src="https://user-images.githubusercontent.com/3378368/231641334-db462f81-354d-4876-adb6-1458cacd0e1d.png">

_Originally posted by @xjbdjay in https://github.com/clusternet/clusternet/issues/656#issuecomment-1506280673_

**Comment by dixudx** [comment]
cc @@xjbdjay

**Comment by dixudx** [comment]
This bug was introduced by #593 since v0.15.0.

**Comment by xjbdjay** [comment]
> 

ok, let me try.

**Comment by jasine** [comment]
@dixudx  same issue, Is it possible to release a bug fix version for this issue before v0.16.0

**Comment by dixudx** [comment]
A patch version v0.15.1 had already been released.

cc @jasine @xjbdjay
