### ISSUE TITLE
only one child cluster are approved after installing with ./local-running.sh

### ISSUE THREAD

**Issue by zhonghuali** [clusternet/clusternet#676]
#### What happened:
1.Followed the steps with install with ./local-running.sh of https://clusternet.io/docs/quick-start/
2. Checking Cluster Registration
run kubectl get clsrr
NAME                                              CLUSTER ID                             STATUS     AGE
clusternet-3f161534-a83e-4bc8-96ba-6d874e4a4316   3f161534-a83e-4bc8-96ba-6d874e4a4316   Approved   16h

4. the results is one child cluster.  Should it return 3 child clusters? why it's only one child cluster,child1 ?

the other child clusters not ready or not be approved,  what's happend?

#### What you expected to happen:
It should return all of child clusters . not sure if it's my misunderstand.

#### Environment:
- Clusternet version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
 "rhel centos fedora"

- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
@zhonghuali Please run with `kind get clusters` to check whether kind clusters are running well.

Sometime, kind pods fail to spin up with errors “too many open files”. Please follow [some-known-issues](https://clusternet.io/docs/quick-start/#some-known-issues) to help resolve it.

**Comment by zhonghuali** [comment]
my machine setting:
fs.inotify.max_user_watches=500000
fs.inotify.max_user_instances=128

changed to :
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl fs.inotify.max_user_instances=512

then the child cluster agent pod startup, this issue gone.

Thanks a lot
