### ISSUE TITLE
the example/scheduling-with-mcs-api doesn't work

### ISSUE THREAD

**Issue by xjbdjay** [clusternet/clusternet#678]
#### What happened:
It did not create derived service.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/3378368/236766066-af1ff5b7-f069-480a-b8cd-1bc59c8a02c7.png">

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by xjbdjay** [comment]
> 

yep, It's v0.15.0+

**Comment by xjbdjay** [comment]
> @xjbdjay What's the version of Clusternet? Starting from v0.15.0, a feature gate `MultiClusterService` should be set explicitly.
> 
> cc @lmxia Please take a look. And please help update the documentation to enable feature gate `MultiClusterService` since v0.15.0.

how to enable feature gate MultiClusterService since v0.15.0.

**Comment by dixudx** [comment]
> how to enable feature gate MultiClusterService since v0.15.0.

This feature gate is set on both clusternet-controller-manager and clusternet-agent side. You can enable it by changing the parameter `--feature-gates=xxx,xxx,MultiClusterService=true` of deployments `clusternet-controller-manager` and `clusternet-agent`.

**Comment by xjbdjay** [comment]
> > how to enable feature gate MultiClusterService since v0.15.0.
> 
> This feature gate is set on both clusternet-controller-manager and clusternet-agent side. You can enable it by changing the parameter `--feature-gates=xxx,xxx,MultiClusterService=true` of deployments `clusternet-controller-manager` and `clusternet-agent`.

this issue still exists. Is there any clue?
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/3378368/236791770-5f7c3736-fa1a-4b1c-ab6f-a1e5d2d921fd.png">
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/3378368/236792109-56d85fd7-9d3b-44ba-a789-8b50114df260.png">

**Comment by dixudx** [comment]
@xjbdjay The feature gate `MultiClusterService` should be set on `clusternet-agent` side as well.

**Comment by xjbdjay** [comment]
> @xjbdjay The feature gate `MultiClusterService` should be set on `clusternet-agent` side as well.

agent also be set

**Comment by xjbdjay** [comment]
agent has some err log:
<img width="1907" alt="image" src="https://user-images.githubusercontent.com/3378368/236807883-c9461016-89f3-4c1a-af22-8ad4829d8498.png">

**Comment by dixudx** [comment]
Those rbac rules have been set on `clusternet-agent` side.

https://github.com/clusternet/clusternet/blob/6ed51a2cdcf133b6ddc41d54d89f195fa0bf392c/deploy/agent/clusternet_agent_rbac.yaml#L26-L59

Please help check whether those rbac settings are created in your cluster.

**Comment by xjbdjay** [comment]
> update

fix the agent err after updating rbac. however, the service is still absent.

**Comment by dixudx** [comment]
any detailed logs/events that can help us investigate what's going on?

cc @lmxia

**Comment by xjbdjay** [comment]
> 
agent log:
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/3378368/236980001-b55c3d4e-ced5-4674-a844-2a5ff079159c.png">
controller-manager log:
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/3378368/236980103-d0dd10eb-bae9-42b5-9aea-0bec6eb82db0.png">

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/3378368/236980192-6a24da48-4f90-4394-90ef-783ce8b9fe23.png">

**Comment by xjbdjay** [comment]
@dixudx  can u have a try with `examples/scheduling-with-mcs-api` ? I suspect whether the serviceimport_controller functions.

**Comment by dixudx** [comment]
> there is no log handling serviceimport in controller-manager,

ServiceImport is purely handled on clusternet-agent side.

kindly ping @lmxia for this issue.

**Comment by lmxia** [comment]
I will check, sorry for my latency.

**Comment by lmxia** [comment]
I found there is a log
 `successfully synced Manifest clusternet-reserved serviceimports.default.my-svc` so propabally you did create serviceimport with subcommand `clusternet`, if it's true, just 
` kubectl clusternet delete -f examples/scheduling-with-mcs-api/service-import.yaml`
and `kubectl create -f examples/scheduling-with-mcs-api/service-import.yaml`

**Comment by lmxia** [comment]
@xjbdjay

**Comment by lmxia** [comment]
Close this issue, feel free to reopen it  if the issue not resolved.
