### ISSUE TITLE
how to query resources created in child cluster from parent cluster using client-go

### ISSUE THREAD

**Issue by xjbdjay** [clusternet/clusternet#680]
#### What would you like to be added:
FYI: All operations is written in client-go, including creating resources(a complex helm chart), and querying resources status in child cluster. All these operations is in parent cluster.

Can kindly offer some demos:
1. using client-go to create subscriptions, helm-chart.
2. using client-go to query resources status.

There is no chart status. The radical purpose is how to get the chart status.
<img width="649" alt="image" src="https://user-images.githubusercontent.com/3378368/237029726-d3957b51-368c-4208-ad0f-191484bb47dc.png">

**Comment by xjbdjay** [comment]
another question:
Does proxy function? I see the code `/pkg/controllers/proxies/` is almost empty, only some websocket connection.
The intention of proxy is to send cmd to child clusters from parent cluster?
@dixudx

**Comment by dixudx** [comment]
@xjbdjay Tutorial [Visiting Child Clusters with RBAC](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/) will show you multiple ways to visit child cluster resources directly from parent cluster.

**Comment by xjbdjay** [comment]
> @xjbdjay Tutorial [Visiting Child Clusters with RBAC](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/) will show you multiple ways to visit child cluster resources directly from parent cluster.
<img width="1339" alt="image" src="https://github.com/clusternet/clusternet/assets/3378368/97cb31a8-f947-433e-873b-443f5a383a66">

it can access child clusters if need child kube config. 
What's the meaning of inner address?

**Comment by xjbdjay** [comment]
> 



> @xjbdjay Tutorial [Visiting Child Clusters with RBAC](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/) will show you multiple ways to visit child cluster resources directly from parent cluster.

need other settings? pls help check. @dixudx 
<img width="1175" alt="image" src="https://github.com/clusternet/clusternet/assets/3378368/b8315b47-f1b3-4100-ab2d-f38a392ca8a4">

**Comment by dixudx** [comment]
The IP address `172.20.0.1` is apparently a gateway IP. Please make sure you're setting the right `kube-apiserver` address.

**Comment by xjbdjay** [comment]
> The IP address `172.20.0.1` is apparently a gateway IP. Please make sure you're setting the right `kube-apiserver` address.

how to get the right inner address? I think the address is accessible for agent. So i use the kubernetes service address.

**Comment by dixudx** [comment]
Any addresses that are accessible in child clusters can be used here. If you have no idea on this address, you can get it from `status.apiserverURL` in `ManagedCluster` object.

**Comment by xjbdjay** [comment]
> ManagedCluster
the address is right. @dixudx 
<img width="567" alt="image" src="https://github.com/clusternet/clusternet/assets/3378368/7f233c77-28a3-4b41-bb54-ddff6bbe3d7f">

**Comment by xjbdjay** [comment]
there are some err logs in hub when using this cmd. @dixudx 
<img width="1261" alt="image" src="https://github.com/clusternet/clusternet/assets/3378368/2c2aa686-b49c-453f-ae2d-639988b25130">

**Comment by dixudx** [comment]
> > 
> 
> > @xjbdjay Tutorial [Visiting Child Clusters with RBAC](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/) will show you multiple ways to visit child cluster resources directly from parent cluster.
> 
> need other settings? pls help check. I just replace the address with inner address. @dixudx <img alt="image" width="1175" src="https://user-images.githubusercontent.com/3378368/237261616-b8315b47-f1b3-4100-ab2d-f38a392ca8a4.png">

I wonder to know the command `kc` here is `kubectl clusternet` or simply `kubectl`.

Also please try to make log verbose with `kubectl clusternet --cluster-id=xxx --xxx get ns -v 10`.

**Comment by xjbdjay** [comment]
> > > 
> > 
> > 
> > > @xjbdjay Tutorial [Visiting Child Clusters with RBAC](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/) will show you multiple ways to visit child cluster resources directly from parent cluster.
> > 
> > 
> > need other settings? pls help check. I just replace the address with inner address. @dixudx <img alt="image" width="1175" src="https://user-images.githubusercontent.com/3378368/237261616-b8315b47-f1b3-4100-ab2d-f38a392ca8a4.png">
> 
> I wonder to know the command `kc` here is `kubectl clusternet` or simply `kubectl`.
> 
> Also please try to make log verbose with `kubectl clusternet --cluster-id=xxx --xxx get ns -v 10`.
> 
> And when issuing `kubectl clusternet`, the ip address of child cluster will be auto filled by `clusternet-hub`. So there is no need to modify the server url in child cluster kubeconfig.
kc is alias of `kubectl clusternet` @dixudx 
<img width="1780" alt="image" src="https://github.com/clusternet/clusternet/assets/3378368/188c7f15-c74c-4dfb-a909-02e6be083eb6">
