### ISSUE TITLE
`kubectl clusternet` cannot fetch resource from all namespace 

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#71]
#### What happened:
```shell
➜  ~ kubectl clusternet get deploy -n foo
NAME       CREATED AT
my-nginx   2021-08-17T13:36:31Z
➜  ~ kubectl clusternet get deploy -A
No resources found
```
#### What you expected to happen:
```shell
➜  ~ kubectl clusternet get deploy -A
NAMESPACE            NAME                     CREATED AT
foo                  my-nginx                 2021-08-17T13:36:31Z
```

#### Environment:
```shell
➜  ~ kubectl clusternet version
{
  "gitVersion": "0.2.0",
  "gitCommit": "13d72bbc7b2227a6e24319ca5f62ddbb39094ab9",
  "buildDate": "2021-08-11T12:07:34Z",
  "platform": "linux/amd64"
}
```
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
Please try `kubectl-clusternet` 0.3.0

**Comment by dixudx** [comment]
@DanielXLee This is not a bug.

For `deploy` or `Deployment`, if we run `kubectl clusternet get deploy`, it means we're listing deployments that served by `clusternet-hub`.

**Comment by DanielXLee** [comment]
👌，will try 0.3.0
