### ISSUE TITLE
Unable to manage child clusternet through parent clusternet

### ISSUE THREAD

**Issue by shekhar250723** [clusternet/clusternet#722]
I have created child and parent cluster but unable to manage it.

I have checked this link but it won't be help to me

https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

I have just simple query, how can we manage child clusternet through parent clusternet. Required some proper commands which will be helpful to me to solve this issue. As per clusternet.io documentation. Almost configuration has been done but still my issue not resolve. Please share me some steps which can help me to resolve this issue.

**Comment by dixudx** [comment]
> Required some proper commands which will be helpful to me to solve this issue. As per clusternet.io documentation. Almost configuration has been done but still my issue not resolve. Please share me some steps which can help me to resolve this issue.

What's the problem now? Is it mentioned in https://github.com/clusternet/kubectl-clusternet/issues/12#issuecomment-1669199312?

If your kubeconfig file has multiple Kubernetes contexts, and you want to split them out. You can do as follows.
Now supposing your current kubeconfig file locates at `/some/path/kubeconfig`. And there are two contexts `gke_dulcet-clock-393808_us-central1-c_clusternet-child` and `gke_dulcet-clock-393808_us-central1-c_clusternet-parent`.

```bash
# (optional) we could create a dir
mkdir ~/my-kubeconfigs

# we make a copy first
cp /some/path/kubeconfig ~/my-kubeconfigs/original-kubeconfig

# child kubeconfig
kubectl config set-context gke_dulcet-clock-393808_us-central1-c_clusternet-child --kubeconfig=~/my-kubeconfigs/original-kubeconfig
kubectl config view --raw --kubeconfig=~/my-kubeconfigs/original-kubeconfig > ~/my-kubeconfigs/gke_dulcet-clock-393808_us-central1-c_clusternet-child.kubeconfig

# parent kubeconfig
kubectl config set-context gke_dulcet-clock-393808_us-central1-c_clusternet-parent --kubeconfig=~/my-kubeconfigs/original-kubeconfig
kubectl config view --raw --kubeconfig=~/my-kubeconfigs/original-kubeconfig > ~/my-kubeconfigs/gke_dulcet-clock-393808_us-central1-c_clusternet-parent.kubeconfig
```

All the commands I showed here were all from <https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/>.

**Comment by shekhar250723** [comment]
@dixudx Thanks, needful has been done. What's the next step?

**a@INILPTP087:~$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://35.184.248.122
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-child
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://34.31.127.125
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
contexts:
- context:
    cluster: gke_dulcet-clock-393808_us-central1-c_clusternet-child
    user: gke_dulcet-clock-393808_us-central1-c_clusternet-child
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-child
- context:
    cluster: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
    user: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
- context:
    cluster: ""
    user: ""
  name: –namespace=baz
current-context: gke_dulcet-clock-393808_us-central1-c_clusternet-child
kind: Config
preferences: {}
users:
- name: gke_dulcet-clock-393808_us-central1-c_clusternet-child
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
- name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
a@INILPTP087:~$ kubectl config use-context  gke_dulcet-clock-393808_us-central1-c_clusternet-parent
Switched to context "gke_dulcet-clock-393808_us-central1-c_clusternet-parent".
a@INILPTP087:~$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://35.184.248.122
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-child
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://34.31.127.125
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
contexts:
- context:
    cluster: gke_dulcet-clock-393808_us-central1-c_clusternet-child
    user: gke_dulcet-clock-393808_us-central1-c_clusternet-child
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-child
- context:
    cluster: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
    user: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
- context:
    cluster: ""
    user: ""
  name: –namespace=baz
current-context: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
kind: Config
preferences: {}
users:
- name: gke_dulcet-clock-393808_us-central1-c_clusternet-child
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
- name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true**

**Comment by dixudx** [comment]
@shekhar250723 Follow all the commands I gave above, you will get two separate kubeconfig files for parent and child cluster.

With these two kubeconfig files, you can use in `kubectl clusternet` command lines. All the steps have been well described in the tutorial.

**Comment by dixudx** [comment]
> I have followed mostly steps. Still, I am stuck on this case from the last few weeks.

You're stuck with pure Kubernetes basic issues, instead of Clusternet. I would suggest to get some basic skills on Kubernetes.

You can follow tutorial [Visiting Child Clusters via kubectl-clusternet plugin](https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-kubectl-clusternet/) to interact with child clusters directly by accessing parent cluster.

**Comment by shekhar250723** [comment]
@dixudx Thanks for the understanding.

Getting error on last step to check the child cluster status. 

**Example command-**
$ kubectl clusternet --cluster-id=7dc5966e-6736-48dd-9a82-2e4d74d30443 --child-kubeconfig=./azure-cd-kubeconfig get ns
NAME                STATUS   AGE
clusternet-system   Active   4d20h
default             Active   24d
kube-node-lease     Active   24d
kube-public         Active   24d
kube-system         Active   24d
test-nginx          Active   11d
test-systemd        Active   11d

**Original command-**
:~$ kubectl clusternet --cluster-id=20ef8c64-5f25-4ea2-ad49-60ed82db47d8 --child-kubeconfig=./clusternet-cluster-wl5q9-kube/config get ns
panic: error while loading kubeconfig from file ./clusternet-cluster-wl5q9-kube/config: open ./clusternet-cluster-wl5q9-kube/config: no such file or directory

goroutine 1 [running]:
github.com/clusternet/kubectl-clusternet/pkg/plugin.(*ClusternetOptions).WrapConfigFn(0xc0005c02d0, 0xc0000c58c0)
        /home/runner/work/kubectl-clusternet/kubectl-clusternet/pkg/plugin/clusternet.go:115 +0xb19
k8s.io/cli-runtime/pkg/genericclioptions.(*ConfigFlags).ToRESTConfig(0xc00018d800)
        /home/runner/go/pkg/mod/k8s.io/cli-runtime@v0.23.1/pkg/genericclioptions/config_flags.go:139 +0x42
k8s.io/cli-runtime/pkg/genericclioptions.(*ConfigFlags).toDiscoveryClient(0xc00018d800)
        /home/runner/go/pkg/mod/k8s.io/cli-runtime@v0.23.1/pkg/genericclioptions/config_flags.go:269 +0x33
k8s.io/cli-runtime/pkg/genericclioptions.(*ConfigFlags).toPersistentDiscoveryClient(0xc00018d800)
        /home/runner/go/pkg/mod/k8s.io/cli-runtime@v0.23.1/pkg/genericclioptions/config_flags.go:259 +0xa7
k8s.io/cli-runtime/pkg/genericclioptions.(*ConfigFlags).ToDiscoveryClient(0x8)
        /home/runner/go/pkg/mod/k8s.io/cli-runtime@v0.23.1/pkg/genericclioptions/config_flags.go:249 +0x25
github.com/clusternet/kubectl-clusternet/pkg/plugin.(*ClusternetGetter).ToDiscoveryClient(0x10)
        /home/runner/work/kubectl-clusternet/kubectl-clusternet/pkg/plugin/getter.go:71 +0x22
k8s.io/cli-runtime/pkg/resource.NewBuilder.func1()
        /home/runner/go/pkg/mod/k8s.io/cli-runtime@v0.23.1/pkg/resource/builder.go:206 +0x26
k8s.io/cli-runtime/pkg/resource.(*cachingCategoryExpanderFunc).ToCategoryExpander(0xc00041a340)
        /home/runner/go/pkg/mod/k8s.io/cli-runtime@v0.23.1/pkg/resource/builder.go:1204 +0xa7
k8s.io/cli-runtime/pkg/resource.(*Builder).ReplaceAliases(0xc0005a9900, {0x7fff01c5e4d5, 0x10})
        /home/runner/go/pkg/mod/k8s.io/cli-runtime@v0.23.1/pkg/resource/builder.go:624 +0x102
k8s.io/cli-runtime/pkg/resource.(*Builder).ResourceTypeOrNameArgs(0xc0005a9900, 0x1, {0xc00044e180, 0x12cf129, 0x196ecc0})
        /home/runner/go/pkg/mod/k8s.io/cli-runtime@v0.23.1/pkg/resource/builder.go:594 +0x16d
k8s.io/kubectl/pkg/cmd/get.(*GetOptions).Run(0xc000564690, {0x1bf37e0, 0xc0004ee400}, 0xc0003b2780, {0xc00044e180, 0x1, 0x3})
        /home/runner/go/pkg/mod/github.com/clusternet/kubectl@v0.0.0-20220822030913-1bc1282424d6/pkg/cmd/get/get.go:488 +0x1d6
k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func2(0xc0003b2780, {0xc00044e180, 0x1, 0x3})
        /home/runner/go/pkg/mod/github.com/clusternet/kubectl@v0.0.0-20220822030913-1bc1282424d6/pkg/cmd/get/get.go:181 +0xbc
github.com/spf13/cobra.(*Command).execute(0xc0003b2780, {0xc0000b4840, 0x3, 0x4})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005abb80)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        /home/runner/work/kubectl-clusternet/kubectl-clusternet/cmd/kubectl-clusternet.go:43 +0x16a

**Comment by dixudx** [comment]
> ```kubectl clusternet --cluster-id=20ef8c64-5f25-4ea2-ad49-60ed82db47d8 --child-kubeconfig=./clusternet-cluster-wl5q9-kube/config get ns```
> panic: error while loading kubeconfig from file ./clusternet-cluster-wl5q9-kube/config: open ./clusternet-cluster-wl5q9-kube/config: no such file or directory

The error message had shown very clearly. You're using a nonexistent file.

Could you please use a valid file path. Please! Please! Please!

Running command is not just "COPY and PASTE". Sometimes, you need to understand the cli, what is it for, what is the meaning, also the right parameters.

**Comment by shekhar250723** [comment]
@dixudx Sorry for interpretation again. But I have one doubt in the below link

https://clusternet.io/docs/tutorials/cluster-management/checking-cluster-registration/  

whenever I run the below command. I got the below outpuut  (as per the steps)
Command-- **kubectl get mcls -A**

Output--
**>kubectl get mcls -A
NAMESPACE          NAME                       CLUSTER ID                             SYNC MODE   KUBERNETES         STATUS   AGE
clusternet-9qztb   clusternet-cluster-wl5q9   20ef8c64-5f25-4ea2-ad49-60ed82db47d8   Dual        v1.27.2-gke.1200   True     7d5h**

Then again same command I am trying to run (which is mentioned in visiting clusternet link and getting the same output.
But in the shared link, it's showing different output.
https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-kubectl-clusternet/

**Note: I am running both the commands in parent cluster.** 

Please suggest, where is the problem in above steps. Because I have done the same steps earlier but still getting the same output.

**Comment by dixudx** [comment]
> But in the shared link, it's showing different output.

No worries. They are just sample outputs. The documentations are not written at the same time. That's why we see different outputs.

**Comment by shekhar250723** [comment]
@dixudx Thanks for the support. Issue has been resolved now and we are able to manage child cluster through parent cluster.

**Comment by shekhar250723** [comment]
@dixudx  Thanks for the support. Issue has been resolved now and we are able to manage child cluster through parent cluster but I have only one doubt. Whenever I did restart my system then again kubectl clusternet need to re-install in local system. After that, it will be work.

**$ kubectl clusternet version
{
  "gitVersion": "0.5.0",
  "platform": "darwin/amd64"
}**

**Comment by dixudx** [comment]
> Whenever I did restart my system then again kubectl clusternet need to re-install in local system. After that, it will be work.

You should update your `.bashrc` or `.zshrc` file and append the following line:

```
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
```

and restart your shell.

**This has been clearly said in kubectl krew installation doc.**
