### ISSUE TITLE
helm deploy failed

### ISSUE THREAD

**Issue by lifehacking** [clusternet/clusternet#750]
#### What happened:

    helm(3.12.2) deploy clusternet-hub(0.16.0) on k8s(1.26.8) failed，eg:

E1018 14:08:06.211550   31100 memcache.go:287] couldn't get resource list for shadow/v1alpha1: the server is currently unable to handle the request
E1018 14:08:06.216493   31100 memcache.go:287] couldn't get resource list for proxies.clusternet.io/v1alpha1: the server is currently unable to handle the request
E1018 14:08:06.224392   31100 memcache.go:121] couldn't get resource list for shadow/v1alpha1: the server is currently unable to handle the request
E1018 14:08:06.226429   31100 memcache.go:121] couldn't get resource list for proxies.clusternet.io/v1alpha1: the server is currently unable to handle the request
E1018 14:08:06.267139   31100 memcache.go:287] couldn't get resource list for shadow/v1alpha1: the server is currently unable to handle the request
E1018 14:08:06.276448   31100 memcache.go:287] couldn't get resource list for proxies.clusternet.io/v1alpha1: the server is currently unable to handle the request
E1018 14:08:06.278485   31100 memcache.go:121] couldn't get resource list for shadow/v1alpha1: the server is currently unable to handle the request

#### Environment:
- Helm version: 3.12.2
- Helm charts version: 0.13.0
- Clusternet version:
    - Clusternet-hub version (0.16.0):
- Kubernetes version (1.26.8):
- OS (centos7.9):

**Comment by dixudx** [comment]
@lifehacking Please follow guide [Installing Clusternet on k3s](https://clusternet.io/docs/installation/install-on-k3s/).

In k3s, bootstrapping authentication is not supported by the kube-apiserver in parent cluster, i.e. --enable-bootstrap-token-auth=false (which defaults to be false), please use serviceaccount token instead.

**Comment by lifehacking** [comment]
@dixudx  thanks

**Comment by dixudx** [comment]
@lifehacking Does the issue still exist?

**Comment by lifehacking** [comment]
@dixudx  sloved
