### ISSUE TITLE
Missing the example to set a valid chartPullSecret

### ISSUE THREAD

**Issue by TanyaSingh-espina** [clusternet/clusternet#799]
If you want to install a helm chart from a private helm repository, please set a valid chartPullSecret by referring [**this example**](https://clusternet.io/docs/tutorials/deploy/templates/helm-chart-private-repo.yaml).

Here in the above page the exaple url redirects to empty page. There is no example to check how things can be implemented. 
Please check this. 

URL for the page is : https://clusternet.io/docs/tutorials/multi-cluster-apps/replication-scheduling-to-multiple-clusters/

**Comment by chxcode** [comment]
This is a valid URL:  [https://github.com/clusternet/clusternet/blob/main/deploy/templates/helm-chart-private-repo.yaml](https://github.com/clusternet/clusternet/blob/main/deploy/templates/helm-chart-private-repo.yaml)
