### ISSUE TITLE
How to tell different child clusters in parent cluster?

### ISSUE THREAD

**Issue by fengye87** [clusternet/clusternet#80]
Whenever a child cluster joins the parent cluster, it would get a generated clusterID. If there're multiple child clusters, how can I tell which clsrr/mcls belongs to which child cluster? Is there anyway I can specify this clusterID in clusternet-agent manifest?

**Comment by dixudx** [comment]
> If there're multiple child clusters, how can I tell which clsrr/mcls belongs to which child cluster?

**Comment by fengye87** [comment]
So the short answer is, I should specify `cluster-reg-name` in the clusternet-agent manifest and match that name with clsrr.Spec.ClusterName to find out the corresponding clusterID?

**Comment by dixudx** [comment]
@fengye87 A short answer is,

```bash
$ kubectl get clsrr -l clusters.clusternet.io/cluster-name=YOUR-CLUSTER-NAME
$ kubectl get mcls -A -l clusters.clusternet.io/cluster-name=YOUR-CLUSTER-NAME
```

If you get your clusterID, you can also query like this,

```bash
$ kubectl get clsrr -l clusters.clusternet.io/cluster-id=YOUR-CLUSTER-ID
$ kubectl get mcls -A -l clusters.clusternet.io/cluster-id=YOUR-CLUSTER-ID
```

**Comment by fengye87** [comment]
@dixudx Got it, thanks! I'm closing this issue.
