### ISSUE TITLE
Orphan mcs-syncer role

### ISSUE THREAD

**Issue by zyue110026** [clusternet/clusternet#814]
We have noticed an instance of an orphan resource in one of your Kubernetes configuration files. Deploying Kubernetes resources that are not being actively used or referenced by any other resources in the cluster can lead to orphan resources. These orphan resources consume unnecessary resources and can potentially cause confusion or clutter within the cluster.  Additionally, we provide anecdotal evidence from [topolvm-topolvm#484](https://github.com/topolvm/topolvm/issues/484) regarding the orphan resource defect.

#### What happened:
role mcs-syncer does not have any role binding
https://github.com/clusternet/clusternet/blob/545fe9b1f32fd68e4433b60323a235054892cd44/deploy/hub/clusternet_hub_rbac.yaml#L18

#### What you expected to happen:

mcs-syncer role should have a role binding, otherwise it is a orphan resource. Or delete mcs-syncer role to avoid deploy orphan resource.

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by lmxia** [comment]
Exactly! That's a role i missed add  but left alone,  could you remove that  orphan role?

**Comment by zyue110026** [comment]
@lmxia I created a pr and removed that orphan role. Please check: https://github.com/clusternet/clusternet/pull/815
