### ISSUE TITLE
v0.17.1 panic when hub starting

### ISSUE THREAD

**Issue by abstractmj** [clusternet/clusternet#816]
#### What happened:

I0801 09:26:43.938440       1 flags.go:64] FLAG: --tls-private-key-file=""
I0801 09:26:43.938444       1 flags.go:64] FLAG: --tls-sni-cert-key="[]"
I0801 09:26:43.938451       1 flags.go:64] FLAG: --v="2"
I0801 09:26:43.938457       1 flags.go:64] FLAG: --version=""
I0801 09:26:43.938461       1 flags.go:64] FLAG: --vmodule=""
I0801 09:26:43.942590       1 hub.go:109] sending events to api server
I0801 09:26:43.942830       1 hub.go:145] starting clusternet-hub ...
I0801 09:26:44.454937       1 serving.go:374] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I0801 09:26:44.456155       1 dynamic_serving_content.go:113] "Loaded a new cert/key pair" name="serving-cert::apiserver.local.config/certificates/apiserver.crt::apiserver.local.config/certificates/apiserver.key"
I0801 09:26:44.874020       1 requestheader_controller.go:244] Loaded a new request header values for RequestHeaderAuthRequestController
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2874ffd]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0xc0003de640?)
        /go/pkg/mod/k8s.io/client-go@v0.29.0/kubernetes/clientset.go:461 +0x1d
github.com/clusternet/clusternet/pkg/hub/options.(*HubServerOptions).recommendedOptionsApplyTo(0xc0003b1d50, 0xc0006b4e00)
        /go/src/github.com/clusternet/clusternet/pkg/hub/options/options.go:247 +0xf0
github.com/clusternet/clusternet/pkg/hub/options.(*HubServerOptions).Config(0xc0003b1d50)
        /go/src/github.com/clusternet/clusternet/pkg/hub/options/options.go:161 +0x625
github.com/clusternet/clusternet/pkg/hub.(*Hub).Run(0xc000a837a0, {0x3f32a10, 0xc0002b9040})
        /go/src/github.com/clusternet/clusternet/pkg/hub/hub.go:146 +0xb4
github.com/clusternet/clusternet/cmd/clusternet-hub/app.NewClusternetHubCmd.func2(0xc0005db400?, {0xc0001b8c00?, 0x4?, 0x3ac1f37?})
        /go/src/github.com/clusternet/clusternet/cmd/clusternet-hub/app/app.go:91 +0x41d
github.com/spf13/cobra.(*Command).execute(0xc000004600, {0xc0000520a0, 0x8, 0x8})
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004600)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
k8s.io/component-base/cli.run(0xc000004600)
        /go/pkg/mod/k8s.io/component-base@v0.29.0/cli/run.go:146 +0x2c5
k8s.io/component-base/cli.Run(0x3f32a10?)
        /go/pkg/mod/k8s.io/component-base@v0.29.0/cli/run.go:46 +0x17
main.main()
        /go/src/github.com/clusternet/clusternet/cmd/clusternet-hub/hub.go:34 +0xc5

#### Environment:
- Clusternet version:
    - Clusternet-hub version: v0.17.1
- Kubernetes version (use `kubectl version`): 1.26
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by abstractmj** [comment]
The same error occurred in v0.17.0

**Comment by levidehaan** [comment]
Yeah so i also got the same error, on EKS.
i changed to 17.0 and that also failed, so i only changed the hib version to 16 and it at least started, so now im rolling it all back to 16 to see if it works.

Then if it does ill build my own docker containers from a local compile with 17 and some debugging and see if i can figure it out, but dont wait for me, give it a go yourself, its pretty straight forward.

**Comment by abstractmj** [comment]
v0.16.0 works well

**Comment by dixudx** [comment]
It seems like that a method got changed in the dependency library.
