### ISSUE TITLE
unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps

### ISSUE THREAD

**Issue by zhaodaiyang0574** [clusternet/clusternet#821]
#### What you expected to happen:
root@localhost:/src/github.com/clusternet/clusternet/hack# ./local-running.sh 
Deleting cluster "parent" ...
Deleted nodes: ["parent-control-plane"]
Creating cluster "parent" ...
 ✓ Ensuring node image (kindest/node:v1.22.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-parent"
You can now use your cluster with:

kubectl cluster-info --context kind-parent --kubeconfig /root/.kube/clusternet/parent.config

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
Context "kind-parent" renamed to "parent".
Cluster "kind-parent" set.
Cluster parent has been initialized
Deleting cluster "child1" ...
Deleted nodes: ["child1-control-plane"]
Creating cluster "child1" ...
 ✓ Ensuring node image (kindest/node:v1.22.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
⢎⡰ Starting control-plane 🕹️ 
⠎⠁ Starting control-plane 🕹️ 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-child1"
You can now use your cluster with:

kubectl cluster-info --context kind-child1 --kubeconfig /root/.kube/clusternet/child1.config

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
Context "kind-child1" renamed to "child1".
Cluster "kind-child1" set.
Cluster child1 has been initialized
Deleting cluster "child2" ...
Deleted nodes: ["child2-control-plane"]
Creating cluster "child2" ...
 ✓ Ensuring node image (kindest/node:v1.22.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
⢎⡠ Starting control-plane 🕹️ 
 ✓ Starting control-plane 🕹️ 
⢀⡱ Installing CNI 🔌 
⢄⡱ Installing CNI 🔌 
⢆⡱ Installing CNI 🔌 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-child2"
You can now use your cluster with:

kubectl cluster-info --context kind-child2 --kubeconfig /root/.kube/clusternet/child2.config

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
Context "kind-child2" renamed to "child2".
Cluster "kind-child2" set.
Cluster child2 has been initialized
Deleting cluster "child3" ...
Deleted nodes: ["child3-control-plane"]
Creating cluster "child3" ...
 ✓ Ensuring node image (kindest/node:v1.22.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-child3"
You can now use your cluster with:

kubectl cluster-info --context kind-child3 --kubeconfig /root/.kube/clusternet/child3.config

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
Context "kind-child3" renamed to "child3".
Cluster "kind-child3" set.
Cluster child3 has been initialized
Connecting cluster networks...
Connecting cluster parent to /root/.kube/clusternet/child1.config
Connecting cluster parent to /root/.kube/clusternet/child2.config
Connecting cluster parent to /root/.kube/clusternet/child3.config
Cluster networks connected
Updating helm repo...
"clusternet" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "clusternet" chart repository
Update Complete. ⎈Happy Helming!⎈
Updating helm finished
Installing clusternet-hub...
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/clusternet.config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/clusternet.config
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.clusterInitBaseName): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps]

#### Environment:
- Clusternet version: 
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`): v1.31.0
- Cloud provider or hardware configuration:  2C4G40G
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.4 LTS
- Kernel (e.g. `uname -a`): 5.15.0-117-generic
- Goland: go1.23.1
- Helm: v3.15.4

**Comment by dixudx** [comment]
> [ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.clusterInitBaseName): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps]

@zhaodaiyang0574 Thanks for pointing out. CRD `ManagedCluster` uses a new feature that is only supported since Kubernetes v1.25.

I've filed a PR #823 to fix this. Please have a try.
