### ISSUE TITLE
Upgrade clusternet version 0.16 --0.17.1---0.17.2，master cluster and child cluster can't connected

### ISSUE THREAD

**Issue by huangyanhong** [clusternet/clusternet#835]
### **step 1 ：clusternet  0.16  error：**
I1204 06:17:13.458356       1 subscription.go:281] successfully synced Subscription "region-demo-middle6/dynamic-dividing-base6"
I1204 06:17:13.458774       1 subscription.go:281] successfully synced Subscription "region-demo-middle6/dynamic-dividing-base6"
E1204 06:17:13.480963       1 feedinventory.go:284] **expected string in workqueue but got klog.ObjectRef{Name:"dynamic-dividing-base6", Namespace:"region-demo-middle6"}**
I1204 06:17:26.981041       1 feedinventory.go:297] [FeedInventory] successfully synced Subscription "region-demo-middle6/dynamic-dividing-base6"
I1204 06:17:26.989202       1 subscription.go:281] successfully synced Subscription "region-demo-middle6/dynamic-dividing-base6"
I1204 06:17:27.001837       1 subscription.go:281] successfully synced Subscription "region-demo-middle6/dynamic-dividing-base6"

**### step 2： upgrade clusternet to   to 0.17.1 ,  but cluster-hub  start failed** 

**### step3 ：upgrade clusternet to 0.17.2 and child agent to 0.17.2，master cluster and child cluster can't connect**

204 09:58:10.677275       1 yacht.go:325] please check whether the advertised apiserver of current child cluster is accessible. the server rejected our request for an unknown reason
E1204 09:58:10.685634       1 memcache.go:265] couldn't get current server API group list: the server rejected our request for an unknown reason
E1204 09:58:10.685680       1 yacht.go:297] failed to deploying Description clusternet-qx2zz/region-demo-middle1-static-d1849647150506594305-generic: please check whether the advertised apiserver of current child cluster is accessible. the server rejected our request for an unknown reason
E1204 09:58:10.685734       1 yacht.go:325] please check whether the advertised apiserver of current child cluster is accessible. the server rejected our request for an unknown reason
E1204 09:58:10.699175       1 memcache.go:265] couldn't get current server API group list: the server rejected our request for an unknown reason
E1204 09:58:10.699218       1 yacht.go:297] failed to deploying Description clusternet-crw9d/region-demo-middle1-dynamic-d1849647150506594304-generic: please check whether the advertised apiserver of current child cluster is accessible. the server rejected our request for an unknown reason
E1204 09:58:10.699246       1 yacht.go:325] please check whether the advertised apiserver of current child cluster is accessible. the server rejected our request for an unknown reason
E1204 09:58:10.722782       1 memcache.go:265] couldn't get current server API group list: the server rejected our request for an unknown reason
E1204 09:58:10.726583       1 memcache.go:265] couldn't get current server API group list: the server rejected our request for an unknown reason
E1204 09:58:10.737693       1 memcache.go:265] couldn't get current server API group list: the server rejected our request for an unknown reason
E1204 09:58:10.779217       1 memcache.go:265] couldn't get current server API group list: the server rejected our request for an unknown reason

#### How to reproduce it (as minimally and precisely as possible):
update clusternet image  from  0.16 to 0.17.1 --- 0.17.2
#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
Here is a workaround:
1. clusternet-hub v0.16.0
2. clsuternet-controller-manager v0.17.2

**Comment by huangyanhong** [comment]
**test result :
clusternet-controller-manager： v0.17.2**
I1209 03:17:43.543517       1 feedinventory.go:340] [FeedInventory] successfully synced Subscription "region-demo-middle6/dynamic-dividing-base7"
I1209 03:17:43.546763       1 subscription.go:235] successfully synced Subscription "region-demo-middle6/dynamic-dividing-base7"
I1209 03:17:43.559318       1 subscription.go:235] successfully synced Subscription "region-demo-middle6/dynamic-dividing-base7"

**clusternet-hub：   v0.16.0**
E1209 03:17:59.393635       1 writers.go:122] apiserver was unable to write a JSON response: http2: stream closed
E1209 03:17:59.393761       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E1209 03:17:59.393858       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="06bfde2d-9248-4102-a7da-3d6287b0e4fc"
E1209 03:17:59.398940       1 writers.go:135] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1209 03:17:59.400187       1 timeout.go:142] post-timeout activity - time-elapsed: 6.200775ms, GET "/apis/shadow/v1alpha1" result: <nil>
E1209 03:17:59.401306       1 writers.go:122] apiserver was unable to write a JSON response: http2: stream closed
E1209 03:17:59.401508       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/shadow/v1alpha1" audit-ID="ab28c0e1-e732-499c-bc76-7f3586341646"

**clusternet-scheduler   v0.16.0**

I1209 03:17:43.542850       1 types.go:105] merge one feed : &{[clusternet-56bqn/k8s-pressure-test clusternet-crw9d/clusternet-cluster-vmvd5 clusternet-qx2zz/clusternet-cluster-47cvs] map[v1/Namespace/region-demo-middle6:[]]}
I1209 03:17:43.542914       1 types.go:105] merge one feed : &{[clusternet-56bqn/k8s-pressure-test clusternet-crw9d/clusternet-cluster-vmvd5 clusternet-qx2zz/clusternet-cluster-47cvs] map[v1/Secret/region-demo-middle6/*******:[]]}


**clusternet-agent: v0.16.0**


**can't sub namespace  and secret  to child cluster**

[root@**.**.**.** clusternet]# kubectl  get sub dynamic-dividing-base7 -n region-demo-middle6 -o yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.clusternet.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"dynamic-dividing-base7","namespace":"region-demo-middle6"},"spec":{"dividingScheduling":{"dynamicDividing":{"strategy":"Spread"},"type":"Dynamic"},"feeds":[{"apiVersion":"v1","kind":"Namespace","name":"region-demo-middle6"},{"apiVersion":"v1","kind":"Secret","name":"ali-hb-test-huifutest-com","namespace":"region-demo-middle6"}],"schedulingStrategy":"Dividing","subscribers":[{"clusterAffinity":{"matchExpressions":[{"key":"clusters.clusternet.io/cluster-id","operator":"Exists"}]}}]}}
  creationTimestamp: "2024-12-09T03:17:43Z"
  finalizers:
  - apps.clusternet.io/finalizer
  generation: 1
  labels:
    848443b0-1cae-49d8-94ee-b99128bf8f83: Subscription
  name: dynamic-dividing-base7
  namespace: region-demo-middle6
  resourceVersion: "219684667"
  uid: 848443b0-1cae-49d8-94ee-b99128bf8f83
spec:
  dividingScheduling:
    dynamicDividing:
      strategy: Spread
    type: Dynamic
  feeds:
  - apiVersion: v1
    kind: Namespace
    name: region-demo-middle6
  - apiVersion: v1
    kind: Secret
    name: ali-hb-test-huifutest-com
    namespace: region-demo-middle6
  preemptionPolicy: PreemptLowerPriority
  schedulerName: default
  schedulingStrategy: Dividing
  subscribers:
  - clusterAffinity:
      matchExpressions:
      - key: clusters.clusternet.io/cluster-id
        operator: Exists
status:
  replicas:
    v1/Namespace/region-demo-middle6: []
    v1/Secret/region-demo-middle6/ali-hb-test-huifutest-com: []
  specHash: 1928827238
[root@**.**.**.** clusternet]# kubectl  get desc -A 
NAMESPACE          NAME                                                               DEPLOYER   STATUS    AGE
clusternet-56bqn   region-demo-middle1-static-d1849647150506594306-generic            Generic    Success   3d1h
clusternet-56bqn   region-demo-middle5-static-dividing-base5-generic                  Generic    Success   3d1h
clusternet-crw9d   region-demo-middle1-static-d1849647150506594305-generic            Generic    Success   16d
clusternet-crw9d   region-demo-middle1-static-d1849647150506594306-generic            Generic    Success   4d22h
clusternet-crw9d   region-demo-middle1-static-d1849647150506594307-generic            Generic    Success   12d
clusternet-crw9d   region-demo-middle1-static-dividing-base-generic                   Generic    Success   16d
clusternet-crw9d   region-demo-middle1-static-dividing-scheduling-region305-generic   Generic    Success   16d
clusternet-crw9d   region-demo-middle4-static-dividing-base4-generic                  Generic    Success   5d1h
clusternet-crw9d   region-demo-middle5-static-dividing-base5-generic                  Generic    Success   5d1h
clusternet-qx2zz   region-demo-middle1-dynamic-d1849647150506594304-generic           Generic    Failure   16d
clusternet-qx2zz   region-demo-middle1-static-d1849647150506594305-generic            Generic    Success   16d
clusternet-qx2zz   region-demo-middle1-static-d1849647150506594306-generic            Generic    Success   4d22h
clusternet-qx2zz   region-demo-middle1-static-d1849647150506594307-generic            Generic    Success   12d
clusternet-qx2zz   region-demo-middle1-static-dividing-base-generic                   Generic    Success   16d
clusternet-qx2zz   region-demo-middle1-static-dividing-scheduling-region305-generic   Generic    Success   16d
clusternet-qx2zz   region-demo-middle4-static-dividing-base4-generic                  Generic    Success   5d1h
clusternet-qx2zz   region-demo-middle5-static-dividing-base5-generic                  Generic    Success   5d1h
