### ISSUE TITLE
update hub websocket connected  failed 

### ISSUE THREAD

**Issue by huangyanhong** [clusternet/clusternet#842]
#### What happened:
update  clusternet to v0.17.2 
child cluster  agent can't connect webocket to parents cluster 

rollback clusternet-hub to 0.16.0  child cluster  agent can connect webocket to parents cluster 

#### What you expected to happen:
child cluster  agent can connect webocket to parents cluster 

#### How to reproduce it (as minimally and precisely as possible):
parents cluster k8s 1.26.3  child cluster k8s 1.24.6
#### Anything else we need to know?:
log：
ime="2024-12-11T08:20:20Z" level=info msg="Connecting to proxy" url="wss://192.168.**.**:6443/apis/proxies.clusternet.io/v1alpha1/sockets/c74f63e1-77aa-4d90-bc50-d1e1f60a537f"
W1211 08:20:22.597795       1 clusterstatus_controller.go:147] failed to discover cluster CIDR: can't get pod ip range
W1211 08:20:22.597837       1 clusterstatus_controller.go:154] failed to discover service CIDR: can't get service ip range
time="2024-12-11T08:20:30Z" level=error msg="Failed to connect to proxy. Response status: 403 - 403 Forbidden. Response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"sockets.proxies.clusternet.io \\\"c74f63e1-77aa-4d90-bc50-d1e1f60a537f\\\" is forbidden: not yet ready to handle request\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"c74f63e1-77aa-4d90-bc50-d1e1f60a537f\",\"group\":\"proxies.clusternet.io\",\"kind\":\"sockets\"},\"code\":403}\n" error="websocket: bad handshake"
time="2024-12-11T08:20:30Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
E1211 08:20:35.688539       1 socket_controller.go:103] websocket connection error: websocket: bad handshake
time="2024-12-11T08:20:41Z" level=info msg="Connecting to proxy" url="wss://192.168.**.**:6443/apis/proxies.clusternet.io/v1alpha1/sockets/c74f63e1-77aa-4d90-bc50-d1e1f60a537f"
W1211 08:20:42.619802       1 clusterstatus_controller.go:147] failed to discover cluster CIDR: can't get pod ip range
W1211 08:20:42.619844       1 clusterstatus_controller.go:154] failed to discover service CIDR: can't get service ip range
time="2024-12-11T08:20:51Z" level=error msg="Failed to connect to proxy. Response status: 403 - 403 Forbidden. Response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"sockets.proxies.clusternet.io \\\"c74f63e1-77aa-4d90-bc50-d1e1f60a537f\\\" is forbidden: not yet ready to handle request\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"c74f63e1-77aa-4d90-bc50-d1e1f60a537f\",\"group\":\"proxies.clusternet.io\",\"kind\":\"sockets\"},\"code\":403}\n" error="websocket: bad handshake"
time="2024-12-11T08:20:51Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
E1211 08:20:56.875156       1 socket_controller.go:103] websocket connection error: websocket: bad handshake
W1211 08:21:02.645870       1 clusterstatus_controller.go:147] failed to discover cluster CIDR: can't get pod ip range
W1211 08:21:02.645913       1 clusterstatus_controller.go:154] failed to discover service CIDR: can't get service ip range

#### Environment:
- Clusternet version: 
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
```
W1218 10:08:05.649936   12342 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ValidatingAdmissionPolicy: the server could not find the requested resource
E1218 10:08:05.650010   12342 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ValidatingAdmissionPolicy: failed to list *v1.ValidatingAdmissionPolicy: the server could not find the requested resource
W1218 10:08:05.651096   12342 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ValidatingAdmissionPolicyBinding: the server could not find the requested resource
E1218 10:08:05.651121   12342 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ValidatingAdmissionPolicyBinding: failed to list *v1.ValidatingAdmissionPolicyBinding: the server could not find the requested resource
```

Clusternet v0.17 used k8s.io/api with `v1beta1.ValidatingAdmissionPolicy`, which was not supported by k8s 1.26.3 (`v1alpha1.ValidatingAdmissionPolicy`). That's the reason why this happens. @huangyanhong

**Comment by dixudx** [comment]
Fixes with $852
