### ISSUE TITLE
Clarification on scaling limitations and performance considerations

### ISSUE THREAD

**Issue by clarkmcc** [clusternet/clusternet#85]
The project README currently states

https://github.com/clusternet/clusternet/blob/2e6e481b21e7e69ebc2371a3f05aa1f754c98b41/README.md#L16-L17

"thousands of millions" would be "billions" of clusters. Can this project really scale that high? Do you have any performance benchmarks to substantiate the claim? And do you have any metrics on what kind of resources this would cost?

The reason I ask is we have thousands (potentially hundreds of thousands) of agents that we'd like to manage in one central hub. This project appears to do what we need it to do, but the claims seem outlandish (sorry if I sounds skeptical) given that Kubernetes itself has much more [conservative limitations](https://kubernetes.io/docs/setup/best-practices/cluster-large/) as to the number of resources it can manage and reconcile in a timely manner.

**Comment by dixudx** [comment]
The design goal of Clusternet is to support as many Kubernetes clusters as practically required. This in fact is a major differentiator of Clusternet, compared to many other multi-cluster Kubernetes solutions.

Currently we're still doing performance optimizations and enhancements. Related benchmarks will be given in v0.5.0. 

Yes, you are very right that 'hundreds of millions' is an exaggerated expression for the current state of the project. While we do have a dream to manage 'billions of things' (as in IoT), for now we want to be more accurate. We will update the README accordingly. Thank you so much for pointing out. We are eager to know more about your use case with thousands (hundreds of thousands) of agents.

**Comment by dixudx** [comment]
@clarkmcc Recently I did a perf test on `clusternet-hub`, as below.

![image](https://user-images.githubusercontent.com/5449021/187183155-f0259171-fc9e-45a8-95f8-159c6540dab6.png)

In the perf test, clusternet-hub and kube-apiserver are running with single instance. When managing 2k clusters, `clusternet-hub` takes about 250 MB memory, while `kube-apiserver` takes about 1GB, the watch latency on sub-cluster resources reaches about 600 ms.

Both `clusternet-hub` and `kube-apiserver` are stateless. With more replicas the latency could be reduced as well.

Also I've run perf tests with a larger scale, managing 1M clusters (one cluster = one clusternet-agent goroutine), single `clusternet-hub` (I run 30 replicas of this) agent can manage ~40k clusters.
