### ISSUE TITLE
clusternet-agent need edge-system 

### ISSUE THREAD

**Issue by TomatoAres** [clusternet/clusternet#9]
#### What happened:

When I deploy clusternet-agent, the container logs error:

```log
E0626 13:41:08.159174       1 leaderelection.go:329] error initially creating leader election record: namespaces "edge-system" not found
```

#### What you expected to happen:

No error log, no need namespace edge-system

#### How to reproduce it (as minimally and precisely as possible):

With docker image: `ghcr.io/clusternet/clusternet-agent :v0.1.0`, you will reproduce it.

Because I haven't find any code about edge-system, and I find there was a default namespace named edge-system [#4 ].

Maybe we need update the image in ghcr.io.

**Comment by dixudx** [comment]
@TomatoAres Please follow v0.1.0 doc.

#4 will be released into v0.2.0 recently.
