### ISSUE TITLE
clusternet-hub pod stays in ContainerCreating

### ISSUE THREAD

**Issue by Sad-polar-bear** [clusternet/clusternet#91]
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:20:12Z"
    message: Marking condition "cloud.tencent.com/load-balancer-backendgroup-ready"
      to True.
    reason: LoadBalancerNetworkGroupReady
    status: "True"
    type: cloud.tencent.com/load-balancer-backendgroup-ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:20:12Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:20:12Z"
    message: 'containers with unready status: [clusternet-hub]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:20:12Z"
    message: 'containers with unready status: [clusternet-hub]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:20:12Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: ghcr.io/clusternet/clusternet-hub:v0.3.0
    imageID: ""
    lastState: {}
    name: clusternet-hub
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 10.228.49.71
  phase: Pending
  qosClass: BestEffort
  startTime: "2021-08-30T09:20:12Z"

**Comment by dixudx** [comment]
@Sad-polar-bear Actually this is an issue for your clusters.

Please check the event of this pod and the kubelet log running on `10.228.49.71`.

**Comment by Sad-polar-bear** [comment]
I have solved the problem,thanks
